### ISSUE TITLE
Complete Support for TYT MD-UV390

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#1]
Things to be implemented: 
 - [x] GPS system representation in codeplug
 - [x] CSV Database representation in codeplug
 - [x] Implement setting for monitor button.
 - [x] More meaningful default settings. 
 - [x] Verify implementation.

**Comment by DC7IA** [comment]
UV390 sounds similar to MD390, are those radios compatible?
Looking at some photos, it looks exactly the same.

I've got an MD390G (MD390 + GPS)... Would I be able to flash it?

**Comment by hmatuschek** [comment]
To my knowledge, these are two different radios. Also Serges dmrconfig implements two different devices for the TYT MD-380 and the TYT MD-UV380. However, they are similar enough that it should be easy to add support for it based on my UV390 and Serges implementation of the MD-380.

**Comment by hmatuschek** [comment]
Finally fixed call-sign DB for TyT UV390 / Retevis RT3S.
