### ISSUE TITLE
Support all band selections of AT-D878UV

### ISSUE THREAD

**Issue by reald** [hmatuschek/qdmr#108]
Usable frequency range depends on selected band plan:

   - BS - Band Select: 
                       0x00 Rx: 400-480 136-174 Tx:400-480 136-174
                       0x01 Rx: 400-480 136-174 Tx:400-480 136-174 (12,5KHz Only)
                       0x02 Rx: 430-440 136-174 Tx:430-440 136-174
                       0x03 Rx: 400-480 136-174 Tx:430-440 144-146
                       0x04 Rx: 440-480 136-174 Tx:440-480 136-174
                       0x05 Rx: 440-480 144-146 Tx:440-480 144-146
                       0x06 Rx: 446-447 136-174 Tx:446-447 136-174
                       0x07 Rx: 400-480 136-174 Tx:420-450 144-148
                       0x08 Rx: 400-470 136-174 Tx:400-470 136-174
                       0x09 Rx: 430-432 144-146 Tx:430-432 144-146
                       0x0a Rx: 400-480 136-174 Tx:430-450 144-148
                       0x0b Rx: 400-520 136-174 Tx:400-520 136-174
                       0x0c Rx: 400-490 136-174 Tx:400-490 136-174
                       0x0d Rx: 400-480 136-174 Tx:403-470 136-174
                       0x0e Rx: 400-520 220-225 136-174 Tx:400-520 220-225 136-174
                       0x0f Rx: 420-520 144-148 Tx:420-520 144-148
                       0x10 Rx: 430-440 144-147 Tx:430-440 144-147
                       0x11 Rx: 430-440 136-174 Tx:136-174

At the moment e.g. some frequency areas of BS=14 are not supported/verify before flashing fails.

**Comment by reald** [comment]
2 more things:
- "Ignore frequency limits" seems not to help for D878UV if a channel in 220 Mhz band is set. => Programming not possible.
- Verify is not possible, too.

**Comment by hmatuschek** [comment]
Ok, fixed the issue with disabling the limit checks. I am currently reworking the way radios are detected. This will allow me to adapt the frequency limits on what ever the radio responds. Also, this will fix an issue with other radios.
