### ISSUE TITLE
Add function to allow users to upload radioid database by country

### ISSUE THREAD

**Issue by zl1lw** [hmatuschek/qdmr#110]
Please consider adding a function in the software to allow the user to choose which country database to upload to the radio from the bulk radioid.net database as this database has grown beyond most radio's storage capabilities.
Many thanks.

**Comment by hmatuschek** [comment]
Added some options to the settings menu. First, you are now able to limit the number of entries in the DB, if not limited the maximum number will be used. Additionally, you can now specify whether to use your DMR ID or a set of DMR ID prefixes for the selection of call-sign DB entries. This feature will be part of the 0.8.1 release.
