### ISSUE TITLE
D878UV: Rx Tone not supported

### ISSUE THREAD

**Issue by reald** [hmatuschek/qdmr#111]
When reading a codeplug from D878UV the RxTone setting is lost (always "-"). TxTone works.

```
Analog  Name                Receive   Transmit   Power Scan TOT RO Admit  Squelch RxTone TxTone Width APRS
[...]
10      "G-NET 2"           145.45000 145.45000  High  -    -   -  -      1       -      79.9   12.5  1
```

**Comment by hmatuschek** [comment]
I cannot reproduce it here for now. To which frequency was it set?

**Comment by reald** [comment]
RxTone was 79.9 Hz like this:

```
Analog  Name                Receive   Transmit   Power Scan TOT RO Admit  Squelch RxTone TxTone Width APRS
[...]
10      "G-NET 2"           145.45000 145.45000  High  -    -   -  -      1       79.9   79.9   12.5  1
```

Steps to reproduce:
- Set RxTone of an analog channel to 79.9 Hz in Anytone CPS
- Flash Codeplug with Anytone CPS to D878UV. 79.9 Hz RxTone is active in the device.
- Read Codeplug with qdmr
- RxTone is lost

Selecting an RxTone in qdmr and saving it to disk works. Also reloading this codeplug from disk works. Have not tried to flash an RxTone with qdmr yet.

**Comment by hmatuschek** [comment]
Ahh, yes. This way I can reproduce it. 

However, it is actually intentional: Have you set the Squelch mode to CTCSS/DCS? 

In my opinion, the RX CTCSS/DCS makes no sense if it does not control the squelch. As the internal codeplug representation in qdmr has no field to hold the squelch control separately from the RX CTCSS/DCS, I interpret a carrier based squelch as a disabled RX CTCSS/DCS.

**Comment by hmatuschek** [comment]
There is, however, a situation where a proper CTCSS tone may be read a *disabled*: The D878UV supports non-standard CTCSS frequencies, I do not support in qdmr. In these cases, the CTCSS setting is cleared for both RX and TX.

**Comment by reald** [comment]
Yes, squelch mode was carrier. I changed it for one channel to CTCSS/DCS, flashed it with CPS 1.23, read it back with qdmr and now all (!) RxTones were visible. Then changed squelch mode back to carrier for this one channel, flashed again with CPS 1.23 and read back with qdmr. Still all RXTones are visible! Even after restart of qdmr. Did not change anything else. *confused*

Is the squelch mode visible in qdmr? The "squelch" settings looks more like a squelch level but I think the D878 does not support individual squelch levels for each channel.

But found another issue: qdmr shows 79.9 Hz, but in AT CPS "77 Hz" was selected. Shall I open another issue?

**Comment by hmatuschek** [comment]
Ok, this appears to be another issue with the decoding of the codeplut. We can keep this bug issue for it.

**Comment by hmatuschek** [comment]
Found it. There was an entry missing, so all frequency indices were off by one.
