### ISSUE TITLE
Downloading from an OpenGD77 device (DM1801) fails

### ISSUE THREAD

**Issue by naggie** [hmatuschek/qdmr#112]
Hi Hannes et al,

I've programmed my OpenGD77 DM1801 with the OpenGD77CPS, intending to switch to QDMR which has all the features I require.

The HT is detected and verified OK:
![image](https://user-images.githubusercontent.com/208440/117054975-8eb25300-ad12-11eb-88bb-e41b9f809840.png)

However, about 80% through the codeplug download I get the following message:
![image](https://user-images.githubusercontent.com/208440/117054913-80fccd80-ad12-11eb-9c8b-021ad1197304.png)

I'm running the latest 0.7.2 on Pop!_OS 20.10 (equivalent to Ubuntu at the same version) using the PPA.

Here's the standard output:

![image](https://user-images.githubusercontent.com/208440/117055232-d76a0c00-ad12-11eb-8e05-b2e2ee0267bb.png)

----

I wonder, perhaps the protocol or codeplug format has changed. I'm running revision 70564b8 (Apr 3 2021) of OpenGD77.

Thanks!

**Comment by hmatuschek** [comment]
I could not reproduce it using a OpenRD5R firmware build from June 2020 (30f0fff). Maybe something changed in between versions. To my knowledge, there is no codeplug difference between the OpenRD5R and OpenGD77 firmware builds. Unfortunately, I do not have any newer builds of the firmware. Let me know, if you have a source for the most recent build.

**Comment by naggie** [comment]
Thanks for taking a look @hmatuschek -- I've emailed you the firmware

**Comment by hmatuschek** [comment]
OK, thanks. Received it.

**Comment by hmatuschek** [comment]
OK, I could reproduce it in some way. That is, it works for me most of the times but fails from time to time. Does it fail for you all the time? If so, does the error message always say that it fails at "block 0"? This appears to be a timing issue, so it is hard to debug. If it fails always at block '0' however, it may be a device specific issue that can be addressed easier.

**Comment by naggie** [comment]
It failed all the time when I tried it last time -- I tried about 5 times and every time there was an issue. However, I've just tried it again and 14/15 times it was fine. When it failed, it was `block 0` with the same error every time.

So it seems there could be an intermittent timing issue indeed.

Other possible but unlikely causes:

* Maybe I  changed something in OpenGD77-CPS that affected readability. I only added channels and removed some contacts/groups/zones. Maybe some were invalid
* I notice that the interface is a USB serial device. When developing a microcontroller that interfaced over serial in the past I noticed interference from:
  - Cura, which was trying to probe for printers on all serial ports (grr) but it seems to not affect anything this time
  - The ubuntu package `modemmanager` which did something similar. I had to remove it for my microcontroller project to work and wondered if it could be causing issues here too.
  - The battery was probably at 50 or 60% last time, now it's 94%

Maybe it's the battery level, if it's not a timing issue. I'll certainly try again when the battery is flat.

**Comment by DC7IA** [comment]
I did have the issue with a battery that just came out of the charger. A reboot of the radio made it work somehow... :thinking: 

Tried it on a GD-77, though.

**Comment by DC7IA** [comment]
Okay, it works when I'm downloading within a second or so of turning the radio on. o.O

**Comment by hmatuschek** [comment]
Does it also happen, when you run it with the command-line version? I.e. run
```
dmrconf read test.conf
```
There is an issue with QThreads and QSerialPort. I have to re-open the connection to the radio when using the GUI. OpenGD77 may not like that.

**Comment by hmatuschek** [comment]
With the last commit 3e5ec0b0fd6a981bcf37734533fb498f644bb0f4, this issue may be fixed. Could you checkout the git version and test it? I want to be sure that this issue is fixed before I release a new version.

**Comment by hmatuschek** [comment]
I've released the version 0.8.0 anyway. So, does this issue still exists. If not, I can close this ticket.

**Comment by naggie** [comment]
It seems to have fixed it for me -- I could not reproduce it trying 15 times -- thank you @hmatuschek
