### ISSUE TITLE
Suggestion - Simple filter for views

### ISSUE THREAD

**Issue by khaytsus** [hmatuschek/qdmr#119]
It would be nice to be able to have a simple filter on views, so I could type in "KY4K" or "146.940", that sort of thing, and it filter out what items it shows in the codeplug down to those matches.  It would not change the codeplug of course, but just make it easier to find channels.

The view that would benefit from this most would likely be the Channels, but I could see Contacts also having this.

**Comment by hmatuschek** [comment]
I am a little bit reluctant to implement a filter view for the table as it makes the selection model considerable harder to implement. That is, continuous selections within a filter view will likely not be continuous in the original model. However to find a particular channel try hitting Ctrl+F in the channel table.

**Comment by khaytsus** [comment]
Oh, I really should have tried that, is that documented anywhere?  I don't see it in the menus or in the help but I very well might have missed it.  That seems sufficient for what I need (ie: finding a channel I know I have, but I'm too blind to find it in the list)

**Comment by hmatuschek** [comment]
In fact, it is not documented yet. So I keep this issue open to remind myself to fix the docs.

**Comment by khaytsus** [comment]
Sounds good, thank you so much!  I was somehow unaware of qDMR, I had played with dmrconfig and made a few suggestions/bug reports when he was first developing that with the MD380 but I had no idea qDMR existed until a few weeks ago.  :)  I'm getting a Anytone 878 soon and hopefully I'll be able to migrate my codeplug over using it.

**Comment by khaytsus** [comment]
I'm actually going to attempt to migrate the data from a OpenGD77 radio to the 878.  Hopefully it works out, maybe some tweaks I'll have to make.  Interesting qDMR doesn't support the MD380, I was thinking dmrconfig started with MD380 support.  :)  But none the less I used editcp for it and it worked well, but I've since sold that radio.
