### ISSUE TITLE
LD_LIBRARY_PATH path issue with latest build

### ISSUE THREAD

**Issue by nathwill** [hmatuschek/qdmr#122]
after building 0.8.0 from source per README, qdmr fails to launch without specifying LD_LIBRARY_PATH:

```
[nathwill@wyrd build]$ qdmr 
qdmr: error while loading shared libraries: libdmrconf.so.0.8: cannot open shared object file: No such file or directory
[nathwill@wyrd build]$ 
[nathwill@wyrd build]$ qdmr 
qdmr: error while loading shared libraries: libdmrconf.so.0.8: cannot open shared object file: No such file or directory
[nathwill@wyrd build]$ LD_LIBRARY_PATH=/usr/local/lib64 qdmr 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Debug in /home/nathwill/Code/qdmr/lib/repeaterdatabase.cc@96: Loaded repeater database with 3961 entries from /home/nathwill/.local/share/DM3MAT/qdmr/repeater.json.
Debug in /home/nathwill/Code/qdmr/lib/userdatabase.cc@124: Loaded user database with 198797 entries from /home/nathwill/.local/share/DM3MAT/qdmr/user.json.
Debug in /home/nathwill/Code/qdmr/lib/talkgroupdatabase.cc@140: Loaded talk group database with 1551 entries from /home/nathwill/.local/share/DM3MAT/qdmr/talkgroups.json.
Debug in /home/nathwill/Code/qdmr/src/application.cc@95: Last known position:
```

this had been working previously with 0.7.3

**Comment by hmatuschek** [comment]
This is weird as I haven't touched the CMakeFiles between version 0.7.3 and the current master branch (except for updating the version number). I've just tried it here under ubnuntu and it works. Did you set the install-prefix using `-DCMAKE_INTSALL_PREFIX=[PATH]`?

**Comment by hmatuschek** [comment]
There was a typo in the install instructions. There, the argument was `-DMAKE_INSTALL_PREFIX=/usr/`

**Comment by nathwill** [comment]
yes, from the bash_history the command was `cmake .. -DMAKE_INSTALL_PREFIX=/usr/`

**Comment by nathwill** [comment]
i'm not sure why the behavior changed, as i can see that prior libdmr shared object files were stored in the same location, but i went ahead and added /usr/local/lib64 to the LD_LIBRARY_PATH by creating /etc/ld.so.conf.d/local.conf with the `/usr/local/lib/` and `/usr/local/lib64/` paths. whatever the root cause, this appears to not be an issue in qdmr.
