### ISSUE TITLE
Digital channel frequency input field is too small

### ISSUE THREAD

**Issue by pe1rrr** [hmatuschek/qdmr#128]
When attempting to enter 446.003125 into the channel for a new Digital Channel the field ends at 446.00312, missing the last 6th digit after the decimal.

**Comment by hmatuschek** [comment]
In fact, all radios store the frequency as 8digit BCDs. This only allows a resolution of up to 10Hz. I would not fix this for now as one may assume that qdmr could provide a higher resolution than actually can be programmed to the radio.
