### ISSUE TITLE
GD77 Zone List (Dual VFO issue)

### ISSUE THREAD

**Issue by pe1rrr** [hmatuschek/qdmr#129]
When using the Zone list creator, if the both A and B lists are populated with channels this will result in two separate zones appearing on the GD77 with indentical names. 

E.g 
```
[14] PMR446 Ana.
[15] PMR446 Ana.
```

I can confirm that the GD77 can have a different zone selected for each "VFO" while in "double wait" mode, so this feature works, but it can lead to confusion for the user.

It would be sufficient to warn a GD77 user that using the B-list will create two separate zones on the zone list of the radio.

With the the limited character space available, "Fixing" the zone list to show A/B is quite difficult without truncating the original name (this is already truncated from 'PMR446 Analogue' to 'PMR446 Ana.' by the GD77 display firmware.

Notes: This happens in both GD77 Stock and OpenGD77

**Comment by hmatuschek** [comment]
Yes, this is an issue. The dual-VFO zones are split (if the B list is not empty) into two and the A/B are added to the name. Of cause the name gets truncated if too long. I'll add a warning specifically when creating zones.
