### ISSUE TITLE
GD77 & CTCSS Tones

### ISSUE THREAD

**Issue by pe1rrr** [hmatuschek/qdmr#130]
The list of CTCSS tones in qdmr lacks 71.9hz which would have been required to use repeaters in southern NL, however I am unfortunately unable to test with the local repeater on 2M as it appears they have switched off CTCSS tone functionality!

However- 

The selected tone closest to 71.9hz (71hz) was set manually on the radio.

The codeplug dump from the Stock GD77 radio does not retain this setting at all. 

On the other hand, OpenGD77's codeplug dump includes the CTCSS information for both RX and TX.

This could possibly be a bug in the Stock GD77 firmware or the codeplug dump in dmrconf. I will update this issue when I can check against the stock CPS software.

**Comment by hmatuschek** [comment]
There was certainly a bug encoding 71.9Hz, it was simply stored as 71.0Hz. This bug affected all radios.

**Comment by pe1rrr** [comment]
Update: Confirmed that the CPS of GD77 (Windows) reads CTCSS info from a programmed channel correctly, so issue is likely within qdmr dump process.

**Comment by hmatuschek** [comment]
I've fixed an issue with the 71.9Hz CTCSS frequency, is it still not appearing?

**Comment by pe1rrr** [comment]
> I've fixed an issue with the 71.9Hz CTCSS frequency, is it still not appearing? I've tested it with the CPS file and is works for me.

Yes that is now correct, tested on read and write and checked on radio itself.
