### ISSUE TITLE
OpenGD77 DMR ID Upload not correct

### ISSUE THREAD

**Issue by pe1rrr** [hmatuschek/qdmr#133]
While testing the DMR ID upload on the stock GD77 firmware I also compared with the OpenGD77 firmware, unfortunately it seems that the DMR ID database does not in fact write properly to the radio as no callsigns resolve (at all). However after uploading with the CPS provided by OpenGD77, the DMRID DB works flawlessly.

Observations: 
During upload the CPS of the OpenGD77 CPS issues a screen information that the DMR ID database is being written, when qdmr attempts this, it does not display a message.

The DMR ID selection and available memory depends upon the length of the data being sent to the radio, in the CPS is is possible to adjust the data input from the CSV file to pick anywhere from 5 to 50 characters, and the resulting calculation of possible DMR IDs that will get written to the radio is displayed at the top of the CPS window (included screenshot) 
![OPenGD77CPS](https://user-images.githubusercontent.com/65178473/130403357-99c69901-5195-46c8-9876-3c54438e6f7d.PNG)

Here is wireshark dumps for a 50,000 dump and one of smaller proportions for analysis.
[OpenGD77_DMRID_50k.zip](https://github.com/hmatuschek/qdmr/files/7029730/OpenGD77_DMRID_50k.zip)

**Comment by hmatuschek** [comment]
Yes that is true, qdmr "automagically" selects the DMR IDs nearest to your ID or the selected prefixes under settings. It then fills the available DB slots with these IDs. The OpenGD77 is the only firmware that allows for a variable size entry and thus for a variable number of entries. To this end, I had to fix the size for the OpenGD77 to 19bytes per entry and therefore allowing for approx 13.8k entries. 

It appears that the available size depends on the actual model being used. This poses a problem to be as the firmware does not report the model. I asked for that feature some time ago ([see OpenGD77 forum](http://opengd77.com/viewtopic.php?f=12&t=1486&sid=b36cafca1645304a31c4de118db13898&start=20#p13064)). I may check whether there is a way to check for the model now.

**Comment by hmatuschek** [comment]
I've just fixed an issue with the OpenGD77 call-sign DB. I cannot test it right now, so if one of you could test it? I hope that it fixes the DB for OpenGD77.

**Comment by hmatuschek** [comment]
I would like to fix this issue before releasing the stable version 0.9.0. I've tested it with OpenGD77 on a RD-5R and it appears to work. However, I cannot be sure if OpenGD77 also uses over-the-air Caller Alias.

**Comment by pe1rrr** [comment]
OpenGD77 on gd77 works uploading callsign db, and the radio successfully resolves callsigns selected using the prefix IDs chosen with dmrconf.

Note that upload will fail if the selected channel/frequency is busy, so i'd advise users to select a zone with inactive channels (Maybe make one specifically for updating) and then proceed with the upload with that one selected￼.



￼

**Comment by hmatuschek** [comment]
Thanks for testing it.
