### ISSUE TITLE
Musl libc requires all used headers

### ISSUE THREAD

**Issue by anarchpenguin** [hmatuschek/qdmr#138]
From 4ce605a2df4dcd14b15a87f380b33cb314662326 Mon Sep 17 00:00:00 2001
From: Jory Pratt <anarchy@gentoo.org>
Date: Sun, 25 Jul 2021 18:55:15 -0500
Subject: [PATCH] Add missing sys/types.h header for musl users

cli/progressbar.cc:14:21: error: 'uint' was not declared in this scope; did you mean 'int'?
   14 | void updateProgress(uint percent) {
      |                     ^~~~
      |                     int

Signed-off-by: Jory Pratt <anarchy@gentoo.org>
---
 cli/progressbar.cc | 1 +
 1 file changed, 1 insertion(+)

diff --git a/cli/progressbar.cc b/cli/progressbar.cc
index 4e95b09..6a58daf 100644
--- a/cli/progressbar.cc
+++ b/cli/progressbar.cc
@@ -1,3 +1,4 @@
+#include <sys/types.h>
 #include "progressbar.hh"
 
 void showProgress(uint percent) {
-- 
2.31.1

This is a one line patch to just add sys/types.h glibc includes the header with the kitchen sink this is not the case with musl libc.

**Comment by hmatuschek** [comment]
There are probably other places where this may happen. I usually include cinttypes and therefore cstdint but this does not deliver uint. I should actually use `unsigned` throughout the code.
