### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#156]
Here's documentation for getting packages into Debian:

https://www.debian.org/doc/manuals/maint-guide/

I will later have a look to get an idea how much work that is and tell you what I learn from that. :D

**Comment by DC7IA** [comment]
Just found the time to look at creating Debian packages.

If I build a package myself it does not segfault, unlike the package from the Ubuntu PPA. :thinking:

**Comment by hmatuschek** [comment]
Mhh, I should definitely try to get it into debian. I already subscribed to the Debian Hams mailing list and waiting for the approval of my salsa account to propose a package. I may come back to you for the debian package stuff when I got the account.

**Comment by DC7IA** [comment]
> I may come back to you for the debian package stuff when I got the account.

I'm just learning all the stuff, you definitely know more for now. :D 

I find all documentation, regardless whether Debian or Ubuntu, confusing. It gives too much information without really giving a clear list of what to do and what to look for and where.

I will definitely need a few weekends to figure this out. :thinking:

**Comment by hmatuschek** [comment]
Started a package at salsa: https://salsa.debian.org/dm3mat/qdmr

**Comment by DC7IA** [comment]
Over at IRC, donfede said "there may be a collaboration opportunity ; any dialogue with them?"

Maybe join **#debian-hams** on OFTC ( https://wiki.debian.org/DebianHams here it says irc.debian.org, maybe they're federated?)

**Comment by hmatuschek** [comment]
Ok, thanks for the information. I'll come back to this. It is quiet late now. But the package is basically ready. There are some lintian issues left that I would rather fix with a new release in upstream than patching like wild in the debian package.

**Comment by hmatuschek** [comment]
OK, the majority of the lintian issues are solved. Now comes the hard part: finding a "sponsor" under the debian maintainers to upload the package.

**Comment by DC7IA** [comment]
I've posted that on IRC, maybe someone wants to help out.

**Comment by hmatuschek** [comment]
It is on the way: https://ftp-master.debian.org/new.html

**Comment by hmatuschek** [comment]
Uploaded: http://incoming.debian.org/debian-buildd/pool/main/q/qdmr/

Should appear in *unstable* soon.

**Comment by DC7IA** [comment]
` [2022-02-02] qdmr 0.10.1-2 MIGRATED to testing (Debian testing watch)`

Now it's just a matter of waiting for 19 months and then it'll be in stable. Ubuntu might be a bit earlier. Not sure how exactly that works, but apparently they take some packages from testing when creating a new release.

**Comment by hmatuschek** [comment]
Yes, it appears like it will be included in the next Ubuntu release automatically. As the rest happens automatically, I'll close this issue for now.
