### ISSUE TITLE
idea: automatically remove channels that are out of range

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#157]
An idea for an additional feature:

An option to automatically remove channels that are out of range when writing to a radio.

This allows maintaining a single codeplug for a variety of radios with different ranges.

For example a codeplug containing frequencies in the 2 m and 70 cm amateur radio bands can then be written to a 70 cm radio. The 2 m channels simply aren't used.

Like this:

```
The following changels are out of range. Do you want to omit them when writing to the radio?

[ Yes, all of them ] [ Select channels to omit ] [ Abort writing ]
```

Or maybe something similar.

**Comment by hmatuschek** [comment]
I've just enabled "Discussions" for this repository. Hopefully I can bundle also email discussions there. How about moving this issue there?
