### ISSUE TITLE
Update Radioddity GD77 implementation

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#16]
Although the code-plug is identical to the OpenGD77 one, the interface to the radio differs. Hence I need to get a handheld to test that device finally or someone who is willing to test the implementation.

**Comment by DC7IA** [comment]
What does still need testing after you solved all my bug reports which prevented me from using qdmr?

Make a list and I will try to test it all. :)

**Comment by hmatuschek** [comment]
I meant the original GD77 firmware.

**Comment by hmatuschek** [comment]
The GD77 code-plug implementation appears to be outdated. It needs an update once I get a handheld. I also merge this ticket with #40.

**Comment by hmatuschek** [comment]
@pe1rrr: If you have some spare time, could you get me a wireshark capture of the callsign DB (ID Library) upload? Ideally one capture with only one callsign, one with two and one with all 11k entries? The is the last feature that is actually missing for the GD77 supported by qdmr.

**Comment by pe1rrr** [comment]
[GD77 DMR ID Wiresharks.zip](https://github.com/hmatuschek/qdmr/files/6987307/GD77.DMR.ID.Wiresharks.zip)

I get a warning from the DMR ID tool provided by the vendor that the csv they provide contains more than Maximum of 10920 IDs, this is from the datadump.csv that is included with the GD77 software bundle.

**Comment by hmatuschek** [comment]
Thanks for the capture! I'll keep you updated on the progress.

**Comment by hmatuschek** [comment]
Close that issue now, it is only the call-sign database missing (see #132).
