### ISSUE TITLE
qDMR not compiling in Archlinux

### ISSUE THREAD

**Issue by WolffyTheReal** [hmatuschek/qdmr#161]
![grafik](https://user-images.githubusercontent.com/14053590/139555077-e5794f8b-3d25-436b-a595-c5909a1d4b31.png)
Error occurs when compiling package from AUR.
Kernel: 5.14.10
C/CXX compiler: GNU 11.1.0

**Comment by WolffyTheReal** [comment]
if building directly from git it compiles just fine so i guess its just that AUR is outdated.

**Comment by hmatuschek** [comment]
I've noticed the maintainer of the AUR package (@dannixon).

**Comment by hmatuschek** [comment]
> if building directly from git it compiles just fine so i guess its just that AUR is outdated.

Oh, `chopped` was only introduced with Qt 5.10 but AUR delivers 5.15. Got the newest version of Qt installed?

**Comment by WolffyTheReal** [comment]
> > if building directly from git it compiles just fine so i guess its just that AUR is outdated.
> 
> Oh, `chopped` was only introduced with Qt 5.10 but AUR delivers 5.15. Got the newest version of Qt installed?

Ah, damn ok. Got 5.9.7 installed.
Updating now and trying again.

Thank you for the quick replies.

**Comment by Misaka13514** [comment]
I've got another issue when clean build the package.

![](https://user-images.githubusercontent.com/54669781/139565615-d53d0cb9-7a1c-48c4-a9a7-2def4d27108f.png)

**Comment by hmatuschek** [comment]
The AUR package is missing the new dependency (yaml-cpp) introduced with version 0.9.0-alpha1. I've contacted the maintainer, so I believe it might be fixed soon.

**Comment by DanNixon** [comment]
I've added `yaml-cpp` as a dependency now. Thanks for letting me know it was missing.

**Comment by hmatuschek** [comment]
Thanks @DanNixon for the fast response! Can someone check whether there remain any issue under Arch Linux. If not, I can close the issue.

**Comment by Misaka13514** [comment]
> Thanks @DanNixon for the fast response! Can someone check whether there remain any issue under Arch Linux. If not, I can close the issue.

There seems to be no problem during my build process, you can close the issue.

**Comment by hmatuschek** [comment]
Ok, thanks all.
