### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by pe1rrr** [hmatuschek/qdmr#164]
Still on the gd77 branch, just did a git pull and ran the build exactly the way I did before but now I get errors:

 Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YAML-CPP",
  but CMake did not find one.

  Could not find a package configuration file provided by "YAML-CPP" with any
  of the following names:

    YAML-CPPConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
  "YAML-CPP_DIR" to a directory containing one of the above files.  If
  "YAML-CPP" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/pi/build/qdmr/build/CMakeFiles/CMakeOutput.log".
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YAML-CPP",
  but CMake did not find one.

  Could not find a package configuration file provided by "YAML-CPP" with any
  of the following names:

    YAML-CPPConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
  "YAML-CPP_DIR" to a directory containing one of the above files.  If
  "YAML-CPP" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/pi/build/qdmr/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:248: cmake_check_build_system] Error 1
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YAML-CPP",
  but CMake did not find one.

  Could not find a package configuration file provided by "YAML-CPP" with any
  of the following names:

    YAML-CPPConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
  "YAML-CPP_DIR" to a directory containing one of the above files.  If
  "YAML-CPP" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/pi/build/qdmr/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:248: cmake_check_build_system] Error 1

**Comment by hmatuschek** [comment]
Sorry, the gd77 branch was super old. Moved it up to the same level as master. Also you need the header files for libyaml-cpp (e.g., the libyaml-cpp-dev package under Ubuntu etc). This is a new dependency with version 0.9.0 for the new codeplug format.

**Comment by pe1rrr** [comment]
Succeeded, can close issue

**Comment by hmatuschek** [comment]
Ok.
