### ISSUE TITLE
improve "Add Channel" dialog

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#166]
The "Name" field is a bit small:

![image](https://user-images.githubusercontent.com/26351852/140408399-768367a9-e551-476e-b983-c8cda16cc1ab.png)

I'm not sure what would be a good approach for this. :thinking: 

Right now it's a bit annoying that I have to click all three entries to find the one for the 70 cm and 2 m frequency for a specific repeater.

But definitely something with low priority. :D

**Comment by hmatuschek** [comment]
Making this field wider is surprisingly difficult. Unfortunately, there is no property of the corresponding Qt object that allows me to expand it. However, a wider field would not help with the frequency issues. I could add some information about the band on to the meta data shown in the parenthesis.

**Comment by hmatuschek** [comment]
I've added some band information to the repeater auto-completer. It also detects APRS repeater.

**Comment by DC7IA** [comment]
That's really useful! Nice!
