### ISSUE TITLE
"Edit Zone" dialog only shows DMR channels

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#168]
"Edit Zone" dialog only shows DMR channels on latest commit:

```
commit 6dccd483c013dee2c7041d61f3d5c06b22e75a5a (HEAD -> master, origin/master, origin/HEAD)
Author: Hannes Matuschek <hmatuschek@gmail.com>
Date:   Tue Nov 2 08:32:21 2021 +0100

    Cleanup.
```

I can add FM channels and they appear in the radio and the FM channels are still there after writing, but the "Edit Zone" dialog does not show them.

**Comment by DC7IA** [comment]
After reading back from the radio I can no longer see the FM channel.

I can however see the new channel directly after adding just before reading it back.

**Comment by hmatuschek** [comment]
Could not really reproduce it here. Can you describe it in a bit more detail? Do the FM channels disappear entirely or only in the zone editor?

**Comment by DC7IA** [comment]
Just noticed that the channels get overwritten, I lost two channels writing to the radio.

**Comment by DC7IA** [comment]
Currently I cannot add new FM channels, I just overwrite existing channels.

**Comment by hmatuschek** [comment]
Ok, we have to be more specific (working on the current master branch): 

1. For testing, I created a blank new codeplug.
2. Created a DMR channel.
3. Created a FM channel. DMR channel is still there.
4. Created a new zone and added the DMR channel
5. Edited new zone and added the FM channel to it. 
6. Reopened the editor and both channels are still there.

If this also work for you, then the issue is not in the GUI/ZoneEditor but in the asembly of the codeplug. Then I need to know which radio you are using.

**Comment by DC7IA** [comment]
Editing works. But reading from a GD-77 running OpenGD77, I do not see the FM channels.

If I add one I'll overwrite another one when writing to the radio.

**Comment by hmatuschek** [comment]
Ha, ok. Than another question, to ease my search. QDMR stores the channels in the same order as listed in the channels tab. Is the last one overridden?

**Comment by DC7IA** [comment]
Please try to make a question that is easier to understand.

What last one? Where?

What list of channels where is in the same order as the channels?

**Comment by hmatuschek** [comment]
Does the channel disappear entirely? That is, if you create a channel, write it to the radio and read it back, the channel is gone? 

Or does the channel "only" disappear from the zone? That is, the channel remains in the channel table of QDMR but is not element of the zone anymore?

If the latter happens. Do you appended it to the end of the zone? How many channels are there in the zone already?

**Comment by hmatuschek** [comment]
Ok, got it. The OpenGD77 codeplug derives from the GD77 codeplug. The latter, however, only contains 16 channels while OpenGD77 allows up to 80 channels. I forgot to override the method that populates the binary encoded zone. So only the first 16 channels are added to the zone.

**Comment by hmatuschek** [comment]
Fixed that with the last commit. This likely fixes it. Let me know if it works for you. Also thanks for reporting the issue. I've apparently never put more than 16 channels into a zone.

**Comment by DC7IA** [comment]
Looks like it works again, couldn't reproduce it.

**Comment by DC7IA** [comment]
> How many channels are there in the zone already?

Forty plus the two I added.

**Comment by DC7IA** [comment]
Closing as it seems to be solved, just reopen if you still want to keep the issue for some reason!
