### ISSUE TITLE
Get a working snap image.

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#18]
The QDMR snap now runs but needs a few rights from snapcraft to work properly out-of-the-box:

- [ ] Request an auto-connect to the raw-usb slot.
- [ ] Publish dummy snaps to map USB-serial interfaces to slots for every supported radio
- [ ] Auto-connect to these slots

**Comment by hmatuschek** [comment]
For the time being, there is no reasonable way to gain access to serial ports from a snap package. Consequently, the snap package will never work properly.

**Comment by goldstar611** [comment]
Don't give up!

I helped get CHIRP on the snap store after python2 became deprecated (I know kicking the can down the road isn't helping anybody). 

What appears to work is adding instructions on how users can enable the feature via snap store AND manually connect to raw USB via command line if they choose. https://snapcraft.io/chirp-snap
