### ISSUE TITLE
Erased setting from RT3S?

### ISSUE THREAD

**Issue by greggawatt** [hmatuschek/qdmr#184]
I was writing a codeplug and pushed a plug that I didn't verify first. It seems to have broken the radio in some weird ways.
- Utilities > Radio Settings Only shows clock and voice announcement
- no way to change the zone now

Curious if you have ever seen this. I've also emailed the manufacturer to see if they have any ideas.

**Comment by hmatuschek** [comment]
Uh, interesting! Can you read and attach the binary codeplug from the device using dmrconf?
```
dmrconf read codeplug.dfu
```
Also which firmware version are you running on the device?

Fortunately, I fully reverse engineered the codeplug of the RT3S, so I can initialize codeplugs. Try to write a small codeplug (e.g., the minimal.yaml in the examples directory) using
```
dmrconf write --init-codeplug examples/minimal.yaml
```
This hopefully resets the codeplug to some default values but you loos all your settings. But before, please read the binary one from the device so I can check what went wrong.

**Comment by hmatuschek** [comment]
If you are curious you can inspect the binary codeplug using
```
dmrconf info codeplug.dfu | less
```
The codeplug structure is documented at https://dm3mat.darc.de/qdmr/libdmrconf/classUV390Codeplug.html (scroll down a bit).

**Comment by hmatuschek** [comment]
Tested it on my own RT3S and it worked fine. Which firmware version are you running?
