### ISSUE TITLE
Support for radioddity gd73

### ISSUE THREAD

**Issue by cbsousa** [hmatuschek/qdmr#188]
I have a radioddity gd73. How can I get support. Are there any tests I can do to contribute?

**Comment by hmatuschek** [comment]
Yes, as I do not own this device, I need your help to figure out the VID/PID of the device (using lsusb while the device is connected). 

Then I have to figure out the protocol used to communicate with the device. For this, I need a wireshark capture of the data send to and from the device while a codeplug read and write. See https://wiki.wireshark.org/CaptureSetup/USB on how to capture USB traffic. The content of the codeplug is not that important at that point. You can write and read the default codeplug. 

If the device supports a call-sign DB. I may also need the captures of writing these call-signs to the device. Ideally writing only one, only two and many entries. 

If you are lucky, the protocol is also used by a device that is already supported. Then I only need to figure out the codeplug format. This can usually be done using the binary codeplug files generated by the CPS. However, I will still need a wireshark capture to verify the memory addresses the CPS writes to.

**Comment by cbsousa** [comment]
Bus 001 Device 005: ID 1206:0227 HTMicroChip walkie-talkie-C7000

**Comment by hmatuschek** [comment]
OK, this will likely be a new protocol. However, an interesting one as the C7000 is a *radio-on-a-chip* that is used in many other devices.

**Comment by cbsousa** [comment]
ok. I neet to go to an windows and report you the wireshark connection. I do it soon.

**Comment by hmatuschek** [comment]
I've installed the manufacturer CPS and had a look at the binary codeplug files it creates. It appears like they simply store the stuff that gets written to the device (quiet common for Radioddity). This will make the reverse engineering of the codeplug much easier as I can do it without the device and with the CPS alone.

**Comment by cbsousa** [comment]
[gd73-read and write.zip](https://github.com/hmatuschek/qdmr/files/7876886/gd73-read.and.write.zip)
the wireshark file

**Comment by hmatuschek** [comment]
That was fast. Thanks. It is possible that the device registers itself as a USB Serial device? That is, lookout for a device like /dev/ttyACM0 or so appearing when plugging it in. If so, this makes the implementation much easier as I do not need to use libusb for raw USB access but rather can use the QSerialPort library for platform independent access to the device.

**Comment by hmatuschek** [comment]
Added `gd73` branch for reverse engineering.

**Comment by cbsousa** [comment]
Well, I don't know how to test this. But, just say. I'm comfortable with using the linux terminal.

**Comment by cbsousa** [comment]
I don't now if is interesting, but that's my dmesg output
 2495.389143] usb 1-3: new full-speed USB device number 5 using xhci_hcd
[ 2505.932502] usb 1-3: device descriptor read/64, error -71
[ 2506.180777] usb 1-3: New USB device found, idVendor=1206, idProduct=0227, bcdDevice= 1.00
[ 2506.180786] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2506.180790] usb 1-3: Product: walkie-talkie-C7000
[ 2506.180792] usb 1-3: Manufacturer: HTMicroChip
[ 2506.180795] usb 1-3: SerialNumber: C86000886357FD716A1F2408
[ 2515.014725] audit: type=1100 audit(1642344796.744:141): pid=3021 uid=1000 auid=1000 ses=1 subj==unconfined msg='op=PAM:authentication grantors=pam_faillock,pam_permit,pam_faillock acct="cbsousa" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[ 2515.014861] audit: type=1101 audit(1642344796.744:142): pid=3021 uid=1000 auid=1000 ses=1 subj==unconfined msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="cbsousa" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[ 2515.015658] audit: type=1110 audit(1642344796.744:143): pid=3021 uid=1000 auid=1000 ses=1 subj==unconfined msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'
[ 2515.018029] audit: type=1105 audit(1642344796.747:144): pid=3021 uid=1000 auid=1000 ses=1 subj==unconfined msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/0 res=success'

**Comment by hmatuschek** [comment]
If the device is handled as a serial port by the kernel, it should also appear in `/sys/class/tty` when connected. If not, I need to talk to it using raw usb.

**Comment by cbsousa** [comment]
In /sys/class/tty i don't see any diference! But i'm not sure about what what should i see.

**Comment by hmatuschek** [comment]
Ok, then it is likely not identified as a serial port by the kernel.

**Comment by opie4624** [comment]
Anything I can contribute as well? I have two of these diminutive little guys.

**Comment by hmatuschek** [comment]
Ok here is the todo-list:

- [x] Get the device
- [x] Reverse engineer protocol 
- [ ] Implement protocol
  - [x] Implement codeplug read
  - [ ] Implement codeplug write
- [ ] Reverse engineer codeplug (no device needed, rdt file is 1:1 written memory)
  - [ ] Settings
    - [x] General settings
    - [ ] Tone settings
    - [ ] Button settings
    - [ ] DMR settings
  - [x] Zones
  - [ ] Channels
  - [ ] Contacts
  - [ ] Group lists
  - [ ] Scan lists
  - [ ] Encryption
  - [ ] DTMF signaling
- [ ] Implement codeplug
  - [ ] Contacts
  - [ ] Group lists
  - [ ] Channels
  - [ ] Zones
  - [ ] Scan lists
  - [ ] Extensions
  - [ ] encoding
  - [ ] decoding
- [ ] Tests

**Comment by hmatuschek** [comment]
Ok, the segfault is certainly a bug. However, that the resource is busy, is somewhat out of my control. Is there any other process that might want to talk to the device? Is there a VirtualBox running Windows with that pesky driver?

**Comment by hmatuschek** [comment]
Probably also with udev, at least modem manager can be told to leave a device alone. But I don't know it. Concerning the transfer error: try increasing the delay in `C7000Device::sendRecv`.

**Comment by hmatuschek** [comment]
Do you know `killall`? Avoids the use of complicated grep/awk stuff to kill all instances of a program.

**Comment by hmatuschek** [comment]
Oh, wait. For now, decoding is not implemented yet. You can only read the binary codeplug using the command line tool. E.g., 
```
dmrconf --verbose read gd73_codeplug.dfu
```

**Comment by hmatuschek** [comment]
There is only read and codeplug decoding implemented. Next step is encoding then writing.

**Comment by hmatuschek** [comment]
Similar to the AnyTone devices: compare the speed with the original CPS.

**Comment by hmatuschek** [comment]
> Wohoo! qdmr is reading my GD-73! I was not brave enough to try to _write_ to the radio, but this is looking good! One thing: the contacts seem to be displayed twice - they just repeat from beginning to end. Since this is "work in progress" I will wait with _writing_ until @hmatuschek says it's ok to try. Cool beans!

Fixed contacts being created twice.

**Comment by opie4624** [comment]
I have one on v1.11 and one on v1.06.

**Comment by hmatuschek** [comment]
The radio does. Once you started a codeplug read, the radio will block until it is completed. Just power-cycle the radio. There is no command to interrupt the transfer nor to reboot the radio. The crash, however, should not happen. Also the verify action should not block the radio. I'll have a look at it.

**Comment by hmatuschek** [comment]
Ok, opened a new issue for the crash.
