### ISSUE TITLE
Does not detect OpenGD-77 device

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#19]
Hi,

just installed qdmr as a snap and granted it USB permissions and then tried connecting to my GD-77 running OpenGD-77:

```
Debug in /build/qdmr/parts/qdmr/src/lib/dfu_libusb.cc@38: Try to detect USB DFU interface 483:df11.
Debug in /build/qdmr/parts/qdmr/src/lib/hid_libusb.cc@11: Try to detect USB HID interface 15a2:73.
Debug in /build/qdmr/parts/qdmr/src/lib/usbserial.cc@8: Try to detect USB serial interface 1fc9:94.
Debug in /build/qdmr/parts/qdmr/src/lib/usbserial.cc@16: Found serial port 1fc9:94: ttyACM3 'MCU VIRTUAL COM DEMO'.
Debug in /build/qdmr/parts/qdmr/src/lib/usbserial.cc@22: Cannot open serial port 'ttyACM3': Permission error while locking the device
ERROR in /build/qdmr/parts/qdmr/src/lib/usbserial.cc@61: : Serial port error: (13) Device is not open.
QCoreApplication::postEvent: Unexpected null receiver
```

This is all I get when I click `Detect connected radios.`.

I get a window saying `No known radio detected. Check connection?
Error:detect(): No matching radio found.`.

**Comment by hmatuschek** [comment]
The OpenGD77 implements a serial-over-usb interface for communication. Under most Linux systems, you need to be a member of the "dialout" group to gain access to these devices. Check your group memberships on the command-line with 
```
$ groups
```
if `dialout` is not listed there, you can add yourself to that group with
```
$ sudo adduser YOURUSERNAME dialout
```
If installed as a snap, you may also need to connect the image to the serial-port slot with
```
$ snap connect qdmr:serial-port
```
Let me know, whether the latter step is necessary so I can update the docs.

**Comment by DC7IA** [comment]
Just tried it:

```
$ snap connect qdmr:serial-port
Error: snap "core" has no "serial-port" interface slots
```
And I am already in the group `dialout`.

**Comment by hmatuschek** [comment]
Ah, yes. I remember. Accessing the serial-port from a snap-app is kind of pain in the ass: 

 1.) I would need to get a device-snap into the official distribution that maps the device to a specific device file.
 2.) Then you can link the serial-port plug to that particular device file.

In other words: It is nearly impossible to access some serial device from snaps. I have absolutely no idea why they do not allow for a general access to any serial port like they allow for any USB device.

To this end I would strongly suggest to resort the the DEB package distributed via my PPA.

**Comment by DC7IA** [comment]
That works. :) 

But after reading the codeplug, I cannot write back what I just read (no changes made).

![grafik](https://user-images.githubusercontent.com/26351852/103363685-07cb4080-4abc-11eb-8e68-79978422d796.png)


Should I open a seperate issue for that?

**Comment by DC7IA** [comment]
The limit in the OpenGD77 CPS is 32, by the way.

**Comment by DC7IA** [comment]
There seem to be more issues with zones:

- One zone appears twice
- Other zones are shown having spaces instead of the normal name

**Comment by hmatuschek** [comment]
Ok, concerning the limit of the group list members, that is clearly a bug. Also I restrict the number of group lists to 64. Apparently that can be up to 76 rx group lists. I would suggest to open two new tickets for the issues with the group lists and zones.

**Comment by DC7IA** [comment]
Alright, created three new issues, thank you. :)

**Comment by hmatuschek** [comment]
Updated Readme.md with a5e0f60c0dc6a7114a4a8a181c561233fd18dabe. There is no immediate fix for that right now.
