### ISSUE TITLE
Ver 0.10.0: RD-5r squelch issue with digital channels 

### ISSUE THREAD

**Issue by anollg1** [hmatuschek/qdmr#192]
The debug has failed. 
The squelch problem with the RD-5R radio is still present. The global default value will not be applied. The squelch of digital channels are still in "0". 
But another issue has been added with the new revision: the indicator LED does no longer work while receiving (green) or transmitting (red), caused by disabling the LED in the radio setup by the codeplug.

**Comment by hmatuschek** [comment]
Concerning the squelch setting for the RD5R: The RD5R has a squelch setting for every channel. That is, the global setting is ignored unless explicitly set to *Default* for every channel in the GUI. This setting, however, is lost when writing the codeplug to the device as it does not have any means to encode this. Consequently, whenever a RD5R codeplug is read, every channel will have an individual squelch setting again. However, I can add a button to the GUI to override all per-channel squelch settings. 

Concerning the LED settings, I am currently implementing the device specific settings for Radioddity devices. This will then allow to check and alter these settings.

**Comment by hmatuschek** [comment]
During the implementation of the device specific settings for the Radioddity devices, I've noticed that the radio settings element is somewhat incomplete. Maybe there is actually a bug in the encoding. I keep you informed.

**Comment by hmatuschek** [comment]
I've implemented the device specific general settings for the Radioddity devices. If you enable *Show commercial features* in the settings dialog, they will be shown. When you read a codeplug from the RD5R, these settings are decoded and encoded when writing to the device. If you create a codeplug from scratch, you first need to add the extension to the codeplug by selecting the "radioddity" extension and click "Create". The new extension will then be populated with the default settings.

Looks like
![Bildschirmfoto von 2022-01-17 15-24-20](https://user-images.githubusercontent.com/282387/149787220-700a3f92-a355-4d70-bcdb-c87e982c2155.png)

**Comment by hmatuschek** [comment]
Just reflashed the original firmware onto my RD-5R (had it running the OpenGD77 firmware) and I can confirm the squelch issue.
