### ISSUE TITLE
qdmr is not able to open anytone 878 savefile

### ISSUE THREAD

**Issue by petrus-lt** [hmatuschek/qdmr#193]
Since commit 2ea6590e497981ab43e6ed87fb153b231cb2020b qdmr is unable to open my savefile. It crashes with the following message:

`ERROR in gpssystem.cc@375: 9123:6: Cannot parse APRS system: '<mycallsign> -7' not a valid source call and SSID.`

I don't know why there is a space in there. APRS was configured using anytone CPS, and aprs do works. 

In [lib/gpssystem.cc(339)](https://github.com/hmatuschek/qdmr/blob/master/lib/gpssystem.cc#L339) there is:
`QRegExp pattern("^([A-Z0-9]+)-(1?[0-9])$");`

so I guess this is expected that it fails, but maybe the failure could be 'softer' to accommodate for issues introduced from anytone cps.

I've since remove the trailing space from my callsign so opening a savefile works again.

Radio firmware version : 1.24N

**Comment by hmatuschek** [comment]
Thanks for the hint. I'll fix that in the decoding of the binary codeplug. Making sure that there is no space. The question is, if the firmware needs that space?

**Comment by hmatuschek** [comment]
That would be great. Not that the firmware now requires that space.

**Comment by hmatuschek** [comment]
This is actually a bug in the encoding/decoding of the binary anytone codeplug. There must be a space if the call is less than 6 chars long. I haven't checked it yet but I can imagine that this is actually part of the AX.25 protocol. However, I insert and handle these spaces now. The YAML representation, however, does not use these spaces and I stick to the strict format requirements.

**Comment by hmatuschek** [comment]
Yes, indeed. The AX.25 protocol has a fixed size destination and source address field of 7 bytes. 6bytes call sign and one byte holding the SSID. Unused bytes of the call-sign must be filled with spaces.

**Comment by hmatuschek** [comment]
Should work now.
