### ISSUE TITLE
macOS dark appearence issue

### ISSUE THREAD

**Issue by ra1nb0w** [hmatuschek/qdmr#195]
Just a low priority issue. On macOS the bar icons and Channels table are black on dark. See the image. 
Version: 0.10.1

thank you

<img width="912" alt="Screen Shot 2022-01-22 at 20 12 12" src="https://user-images.githubusercontent.com/1543838/150652296-dfabb514-1186-429c-99a9-05e5be5cdae2.png">

**Comment by hmatuschek** [comment]
Ok, that is useless.

**Comment by hmatuschek** [comment]
A quick fix could be to add
```
<key>NSRequiresAquaSystemAppearance</key>
<string>true</string>
```
to the Info.plist in the application package. However, I'll try to fix that so qdmr gets compatible to dark mode.

**Comment by ra1nb0w** [comment]
I know, but that is a trick. Thank you for the table, it works fine.

**Comment by hmatuschek** [comment]
Could you check if it works now for the icons? Also are there issues with a hi-res display?

**Comment by ra1nb0w** [comment]
The icons are now working fine. Thank you!
The application is working great on Retina (hi-dpi) resolution and 4k display.
The icons are not well defined, as you can see in the following image (see the full scale image), but are sufficient.

Again, thank you very much!

<img width="912" alt="Screen Shot 2022-01-24 at 15 37 17" src="https://user-images.githubusercontent.com/1543838/150803150-9dd35134-69c5-4641-ab5a-a19d2fba9b53.png">

**Comment by hmatuschek** [comment]
OK, thanks. Glad that it works. Qt does not know about light/dark modes. I basically query the default palette and compare the brightness of the foreground and background colors to detect a dark palette.

**Comment by ra1nb0w** [comment]
I saw from the code. I remember that someone was using `QEvent::PaletteChange` to notify the application when the palette was changed at runtime but it is useless in our case. If that happen, restart the application :)

again, thank you for your time and for this great application.
