### ISSUE TITLE
Add channel doe not appear to be localizing

### ISSUE THREAD

**Issue by rd0fun** [hmatuschek/qdmr#202]
When I add my locator in preferences and Refresh Repeater DB, I don't seem to get any new repeaters, nor do I get any local repeaters.

I've also noted that you can only search on repeater callsign and not on the location text in parenthesis, can that be a feature request?

**Comment by hmatuschek** [comment]
Have you checked if there are any local repeaters in https://repeatermap.de, which is used as the data source?

**Comment by rd0fun** [comment]
OK my fault. I made an assumption. I looked at repeaterbook.com not
repeatermap.de.

So, is there a way to change the data source?

Thank you.

**Comment by rd0fun** [comment]
Apologies, I found the discussion here: https://github.com/hmatuschek/qdmr/discussions/170

Would be great to see this progress. Thanks for a great project!
