### ISSUE TITLE
Anytone CPS 1.26 zone hide

### ISSUE THREAD

**Issue by petrus-lt** [hmatuschek/qdmr#203]
After upgrading my d878uv from 1.24N to 1.26 I was unable to change zones with up and down buttons. 

There is now a new zone setting, "Zone Hide", which is enabled by default. 

![CPS](https://pix.milkywan.fr/S3fIyGr6.png)

Unticking this check box makes the zone available again with up/down buttons. 

There doesn't seem to exist a similar option in qdmr (just build as of now). 

Hannes, I can send you my codeplug out of band if you'd like.

**Comment by hmatuschek** [comment]
There is a new memory section at `0x024C1360` of 0x20 bytes, that encodes a bitmap for every zone to be hidden or not (if set to 1 it is hidden). As I did not save that memory section, it got likely filled with 0xff and thus all zones are hidden. This should be fixed now. However, the current implementation just maintains the current setting in the radio. So if zones are hidden, they remain hidden and you may need to use the windows CPS to clear that flag.

**Comment by hmatuschek** [comment]
Added zone extension for AnyTone devices. This should allow to edit the *hidden zone* flag. Untested though.

**Comment by petrus-lt** [comment]
I just updated qdmr, but not sure from the code where this new feature is in the gui? 

I've not seen anything like this in the Zones tab.

**Comment by hmatuschek** [comment]
The device specific settings are part of the commercial features. Enable
them in the settings menu. I should add a specific flag for them.

petrus-lt ***@***.***> schrieb am Sa., 29. Jan. 2022, 15:31:

**Comment by petrus-lt** [comment]
Oh right ok, I see. 

This feature works just fine. I tested it with a zone that was hidden from anytone CPS, it un-hides it as it should.

Thanks Hannes!

**Comment by hmatuschek** [comment]
OK glad it worked. The extension will be included in the next release. So I will close this issue.
