### ISSUE TITLE
D878UV Decode doesn't properly parse analog DCS codes?

### ISSUE THREAD

**Issue by jwjensen** [hmatuschek/qdmr#205]
Reading from a D878UV radio, FW version 1.26, 2 channels, each with DCS code 413N yields the following yaml file:
`dmrconf read d878uv.dfu`
`dmrconf decode --yaml --radio=d878uv d878uv.dfu > d878uv.yaml.txt`
[d878uv.yaml.txt](https://github.com/hmatuschek/qdmr/files/8149532/d878uv.yaml.txt)
I expect the lines:
```
      rxTone: {dcs: 413}
      txTone: {dcs: 413}
```
for both ch1 and ch2.  Found because I downloaded a codeplug from my radio, made changes, then uploaded the changed codeplug.  The DCS codes were dropped from the radio, and my transmissions were not heard by anyone else...

This looks similar to #111, but my C++ skills are very rusty...  I am using qdmr 0.10.1-2 from debian.  I can't attach the .dfu file - github doesn't support it.  I can provide it - it is a simple codeplug with 1 zone, 2 channels.  Here is the info file:
[d878uv.info.txt](https://github.com/hmatuschek/qdmr/files/8149696/d878uv.info.txt)

Thanks for a great project!

**Comment by hmatuschek** [comment]
Thanks for the detailed bug report. I believe that I fixed it with the last commit. Could you verify that?

**Comment by jwjensen** [comment]
`./cli/dmrconf decode --radio=d878uv D878UV/d878uv.dfu --yaml > D878UV/d878uv-fixed.yaml.txt`
(same .dfu file) correctly produces yaml file
[d878uv-fixed.yaml.txt](https://github.com/hmatuschek/qdmr/files/8153347/d878uv-fixed.yaml.txt)
As expected.  I will try some other corner cases and flashing the radio tonight.  Thanks for the quick fix.

**Comment by jwjensen** [comment]
Sorry for the delay.  I did flash the radio with a variety of CTSCC and DCS (both N and I) codes, then read them back successfully.  I did not flash every code (I couldn't find a list of all defined codes).
