### ISSUE TITLE
MD380 is detected as DR780

### ISSUE THREAD

**Issue by gariac** [hmatuschek/qdmr#222]
Note this MD380 has been programed by Editcp.  I am on OpenSuse 15..3. I pulled qdmr from the sdsrepo. Rev is 0.10.2. 

Error message:
`Cannot connect to radio: In tyt_interface.cc:44: Unknown TyT device 'DR780'
Terminal dump:
`qdmr
Debug in application.cc@812: Set icon theme to 'light'.
Info in repeaterbookcompleter.cc@302: Cannot open repeater cache '/home/mrg/.local/share/DM3MAT/qdmr/repeaterbook.cache.json'.
Debug in userdatabase.cc@124: Loaded user database with 217541 entries from /home/mrg/.local/share/DM3MAT/qdmr/user.json.
Debug in talkgroupdatabase.cc@140: Loaded talk group database with 1615 entries from /home/mrg/.local/share/DM3MAT/qdmr/talkgroups.json.
Debug in application.cc@103: Last known position: 
Debug in application.cc@155: Create main window using icon theme 'light'.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
Debug in application.cc@412: Last device is invalid, search for new one.
Debug in usbserial.cc@162: Search for serial port with matching VID:PID 28e9:18a.
Debug in usbserial.cc@162: Search for serial port with matching VID:PID 1fc9:94.
Debug in hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in dfu_libusb.cc@156: Search for DFU devices matching VID:PID 483:df11.
Debug in dfu_libusb.cc@162: Found device on bus=2, device=6 with 483:df11.
Debug in usbdevice.cc@217: Search for a device matching VID:PID 483:df11 at bus 2, device 6.
Debug in usbdevice.cc@228: Found device on bus=2, device=6 with 483:df11.
Debug in radio.cc@55: Try to detect radio at USB device in DFU mode: bus 2, device 6.
Debug in dfu_libusb.cc@75: Try to detect USB DFU interface USB device in DFU mode: bus 2, device 6.
Debug in dfu_libusb.cc@89: Matching device found at bus 2, device 6 with vendor ID 483 and product ID df11.
Debug in dfu_libusb.cc@128: Connected to DFU device USB device in DFU mode: bus 2, device 6.
ERROR in tyt_interface.cc@44: Unknown TyT device 'DR780'.
`

**Comment by hmatuschek** [comment]
Which firmware version are you running on the MD380?

**Comment by hmatuschek** [comment]
See #163. However, the firmware version is still of interest. I would rather close this one and keep #163.

**Comment by gariac** [comment]
Reading from the radio under "version" I am using MD380Tools
version 2018-07-09.  CP vers V01.34.

I don't see issue 222 anymore so hopefully this doesn't bounce.
