### ISSUE TITLE
OpenGD77 DMR ID database format has changed in v2022-02-08

### ISSUE THREAD

**Issue by pgenera** [hmatuschek/qdmr#223]
According to [this post in the forum](https://www.opengd77.com/viewtopic.php?f=13&t=2132#p17708), the "DMR ID Database version number was changed, so you will need to reinstall that."

I spent some time looking for the opengd77 source, but couldn't find it (or at least, the copies of the repo I found predated 2022-02-08 and I couldn't find any relevant changes.

My radio is running 2022-02-08 and has a id db installed by the matching CPS version that works, in the event that I can dump it to be helpful.

**Comment by hmatuschek** [comment]
Ok, thanks for the update. I'll need to figure out, what has been changed in the format.

**Comment by hmatuschek** [comment]
Oh, the database format has changed significantly. I'll need to figure that one out first.

**Comment by hmatuschek** [comment]
Created a single issue (#394) for all OpenGD77 related issues. I need to rewrite it anyway.
