### ISSUE TITLE
D878: Color code behaviour for roaming channels 

### ISSUE THREAD

**Issue by reald** [hmatuschek/qdmr#224]
For roaming channels color codes have not to be set (value is 16 = 0x10 = "No Use"). In the channel list this is treated correctly but not in the channel editing window (15 is shown):

![Screenshot_20220502_182233](https://user-images.githubusercontent.com/1385404/166277562-04cc7c54-4452-4918-a78a-7b5dede5fb06.png)

**Comment by hmatuschek** [comment]
Uh, a special value I've not recognized. Thanks a lot.

**Comment by hmatuschek** [comment]
In fact, this might be difficult to fix as my roaming zones are just lists of references to existing channels. Hence the properties of these roaming channels cannot be set independently. To this end, I may need to implement a dedicated roaming channel, that can override some channel settings.
