### ISSUE TITLE
D878: DTMF contacts broken

### ISSUE THREAD

**Issue by reald** [hmatuschek/qdmr#225]
In the contact list of qdmr DTMF contacts are shown. But the numbers are missing and the names are partly broken:

**qdmr:**
![image](https://user-images.githubusercontent.com/1385404/166289068-64645698-cfff-4cb6-afe0-f1d9366ebc3b.png)

**CPS**:
![image](https://user-images.githubusercontent.com/1385404/166289647-b449d5b5-6b4e-4987-9361-1255f8c399d0.png)

**Comment by hmatuschek** [comment]
Thanks!
