### ISSUE TITLE
TYT MD-UV380: incomplete codeplug read, zones not read, radio unresponsive after write

### ISSUE THREAD

**Issue by KC1OCY** [hmatuschek/qdmr#226]
Using version 0.10.2 on Lubuntu. On prior versions of qdmr I've been able to read from and write to this radio without issue. When using 0.10.2 qdmr did not completely read from the radio. Zones were not properly read from the radio. qdmr will not open a YAML file saved from the read codeplug; it throws the following error:

"Cannot read codeplug from file '/home/tom/Desktop/TYT 04302022.yaml': In configobject.cc:1185: 50225:4: Cannot parse list."

After writing to the radio, the radio would not respond to any button presses. Luckily I had a Windows computer available with the TYT CPS software and a prior codeplug that I could restore from.

**Comment by hmatuschek** [comment]
Oh, this sounds bad. First, we have to figure out if it is an encoding/decoding issue. Could you install the command line version dmrconf? This tool allows to read binary codeplug from the radio with
```
$ dmrconf --verbose read codeplug.dfu
```
In a second step, this codeplug can then be decoded to the yaml format using
```
$ dmrconf --verbose decode --radio=uv380 codeplug.dfu codeplug.yaml
```
Check if the decoded codeplug is somewhat correct. If the decoding fails, could you attach the binary one here?

**Comment by hmatuschek** [comment]
I've just tested it with my RT3S (MD-UV390) running the firmware versions 18.009 and 18.016. Worked fine with both versions. However, there is a bug in verion 0.10.3 (issue #252) that prevents the assembly of the codeplugs for TyT devices. The next release should fix that.

**Comment by KC1OCY** [comment]
I haven’t used it for some time. I switched form Linux to Windows and have
been using N0GSG Contact Manager.


==== Tom Ulrich Sent from my mobile device. Please pardon any typos.

**Comment by hmatuschek** [comment]
Ok, thanks for sorting this one out.
