### ISSUE TITLE
GD-77 - QDMR 0.10.2 - group list edit bug 

### ISSUE THREAD

**Issue by thunderstar5000** [hmatuschek/qdmr#227]
I dicovered a little bug with the option group list. But please recheck, I might be wrong.

This is what happened:

1. Added a new group in dmr contacts.
2. Loaded the codeplug into qdmr.
3. Added the new contact into an existing group list.
4. Saved the codeplug.
5. Uploaded the changed codeplug into the GD-77.

Then I discovered, that the new TG was not added in the group list. 
When i tried to reload from GD-77 back to qdmr, the download hangs at 99 percent.
----------
However, it might be, that something happened during the first download. 
So I overwrote the codeplug in the GD-77 with an older backup one and tried the same again.
Now it worked.

The diefference between the actual and the older one was, the actual one has a group list more (I made two group lists "jo52dh-1" and "jo52dh-2"). Both are nearly identical, with the exception, the one with -1 was created with qdmr, the one with -2 was created by opengd77CPS. 

The reason for creating the second one, is because qdmr can not add any private calls into a group list - this is another issue, I rerported somewhere else.

It would be nice, if someone could be recheck this and confirm it as a real bug.
The other thing with the private calls adding, I hope it to be added in the next version.

Thanks for reading this.

Best regards

Hans

**Comment by hmatuschek** [comment]
Sorry for the late reply, I've been busy at work. However, I believe that this bug is related to the "private-call in group list" issue. Could you read the binary codeplug from the device and decode it separately? This way you can check if this is a communication issue or a decoding issue (I am pretty sure it is the latter). You can do that with the command line version of qdmr.
```
dmrconf --verbose read opengd77_codeplug.dfu
```
and then decode to yaml using
```
dmrconf --verbose decode --radio=opengd77 opengd77_codeplug.dfu opengd77_codeplug.yaml
```
I would expect the latter to fail. If so, could you attach the binary codeplug here? This would help a lot to find the bug.

**Comment by thunderstar5000** [comment]
Am Donnerstag, 4. August 2022, 09:07:59 CEST schrieb Hannes Matuschek:
Hi Hannes,

don't worry, I myself have not much time at the moment as I already wrote.

However, here is the required information:

--------------------

dmrconf --verbose read opengd77_codeplug.dfu

--- snip ----
dmrconf --verbose read opengd77_codeplug.dfu 
Debug in ***@***.***: Autodetect radios. 
Debug in ***@***.***: Search for serial port with matching VID:PID 28e9:18a. 
Debug in ***@***.***: Search for serial port with matching VID:PID 1fc9:94. 
Debug in ***@***.***: Found ttyACM3 (USB 1fc9:94). 
Debug in ***@***.***: Search for HID interfaces matching VID:PID 15a2:73. 
Debug in ***@***.***: Search for DFU devices matching VID:PID 483:df11. 
Debug in ***@***.***: Found 1 device(s): 
Debug in ***@***.***:   Serial interface 'ttyACM3'. 
Debug in ***@***.***: Using device ttyACM3. 
Debug in ***@***.***: Check if serial port ttyACM3 still exisist and has VID:PID 1fc9:94. 
Debug in ***@***.***: Try to detect radio at Serial interface 'ttyACM3'. 
Debug in ***@***.***: Try to open Serial interface 'ttyACM3'. 
Debug in ***@***.***: Openend serial port ttyACM3 with 115200baud. 
[================================================= ] 99% Debug 
in ***@***.***: Serial port will close now. 
Debug in ***@***.***: Save codeplug at 'opengd77_codeplug.dfu'.

--- snap ---

see attached file

see attached file

--------------------

--- snip ---
dmrconf --verbose decode --radio=opengd77 opengd77_codeplug.dfu opengd77_codeplug.yaml

Debug in ***@***.***: Automatically set default radio id to DL4OCJ.
--- snap ---

--------------------

Nothing failed so far. Hope this helps. 

In the meantime there is another opengd77.binj availale, but this did not fix the issue.

Does this help? Please feel free to ask for any more information.


Best regards and 73's 

Hans, DL4OCJ
> Sorry for the late reply, I've been busy at work. However, I believe that
> this bug is related to the "private-call in group list" issue. Could you
> read the binary codeplug from the device and decode it separately? This way
> you can check if this is a communication issue or a decoding issue (I am
> pretty sure it is the latter). You can do that with the command line
> version of qdmr. ```
> 
> ```
> and then decode to yaml using
> ```
> dmrconf --verbose decode --radio=opengd77 opengd77_codeplug.dfu
> opengd77_codeplug.yaml ```
> I would expect the latter to fail. If so, could you attach the binary
> codeplug here? This would help a lot to find the bug.

**Comment by hmatuschek** [comment]
Sorry, the e-mail attachments are not included here in github, when you reply on a notification via mail.

**Comment by hmatuschek** [comment]
Btw, I've just fixed the private-call in group lists issues. In fact, it was possible all the time (checked only for DMR contacts, not the type of the contact). However, the GUI only allowed for adding group calls. Now, it is possible to add private calls to group lists in the GUI and the type of the contact is checked during the assembly of the codeplug. For all but OpenGD77, private calls are ignored.

**Comment by hmatuschek** [comment]
Ok, found it. I only encoded the first 15 entries (like for the RD5R) of the 32 possible contacts in the group list.
