### ISSUE TITLE
OpenGD-77: RX groups are shown twice

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#23]
RX groups are shown twice (no, I haven't programmed them twice :D)

![grafik](https://user-images.githubusercontent.com/26351852/103365778-21bb5200-4ac1-11eb-8430-dc254ea3c807.png)

**Comment by hmatuschek** [comment]
This is particularly interesting as they show not up as duplicates in the command line. Hence I assume they are a GUI issue. Does this still happen?

**Comment by DC7IA** [comment]
Yes. And flashing leads to them being twice on the device also.

**Comment by hmatuschek** [comment]
Is this issue also solved with the latest commit?

**Comment by DC7IA** [comment]
Yup. :D
