### ISSUE TITLE
dmrconf errors when reading

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#24]
```
$ dmrconf read codeplug_opengd77.dfu
ERROR in /build/qdmr-E64IDD/qdmr-0.4.5/lib/usbserial.cc@66: : Serial port will close now.
ERROR in /build/qdmr-E64IDD/qdmr-0.4.5/lib/usbserial.cc@61: : Serial port error: (13) Device is not open.
QCommandLineParser: option not defined: "cpl"
ERROR in /build/qdmr-E64IDD/qdmr-0.4.5/lib/usbserial.cc@66: : Serial port will close now.
```

Another issue I am still trying to reproduce: When using `dmrconf read codeplug_openg77.dfu`, the radio crashes. Will open an issue if I can reproduce that.

**Comment by hmatuschek** [comment]
This is a false alarm, should be fixed anyway but is of low priority.

**Comment by hmatuschek** [comment]
It is still an error. Also false-alarms should not occur. This may put users off.

**Comment by DC7IA** [comment]
I thought you meant "I already know". :)
