### ISSUE TITLE
Support separate RX and TX limits for AnyTone D878UV II (Plus)

### ISSUE THREAD

**Issue by toco** [hmatuschek/qdmr#240]
Depending on the configured bands mode the AT D878UV II Plus has different RX and TX limits according to http://members.optuszoo.com.au/jason.reilly1/868mods.htm#SelectingBands
However, the [current implementation](https://github.com/hmatuschek/qdmr/blob/153f5e03476479ffb13f76313b17e030422f5afd/lib/d578uv_limits.cc#L75-L76) uses the same (TX) limits for both RX and TX. It would be awesome if programming channels with the RX only flag, within the range of allowed RX frequencies (but outside the TX limits) would be correctly verified.

**Comment by hmatuschek** [comment]
Thanks for pointing it out. 

- [ ] Implement separate RX/TX frequency ranges for AnyTone devices.
- [ ] Throw only warning if RX frequency is out of range.
- [ ] Ignore TX frequency if RX only flag is set during verification.

**Comment by hmatuschek** [comment]
Ok, should be fixed in master.
