### ISSUE TITLE
Edit Digital Channel dialog for mixes up Rx and Tx for repeaters from repeater book.

### ISSUE THREAD

**Issue by toco** [hmatuschek/qdmr#241]
Adding a repeater with the auto-fill by name swaps Rx and Tx frequencies.
E.g. if you add [DB0BRB](https://repeaterbook.com/repeaters/callResult.php?call=DB0BRB) the dialog will use 431.887500 for Rx and 439.487500 for Tx.
However according to repeater book, the Tx frequency for the _repeater_ is 439.48750, which should be used as the Rx frequency of the channel.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/272560/185403521-108d1406-128b-42ad-93db-f7f6661832a9.png">

It looks like variable names `tx` and `rx`need to be swapped in line 200 and 201:
https://github.com/hmatuschek/qdmr/blob/e5fb1d62f3bce9b46bac7625efa70f567f5f11f8/src/digitalchanneldialog.cc#L200-L204

The analog dialog doesn't have a similar swap:
https://github.com/hmatuschek/qdmr/blob/e5fb1d62f3bce9b46bac7625efa70f567f5f11f8/src/analogchanneldialog.cc#L179-L188

**Comment by hmatuschek** [comment]
What a stupid mistake of mine. Thanks for pointing it out!
