### ISSUE TITLE
AT-D878UVII, config verification error "Expected reference to a group call digital contact."

### ISSUE THREAD

**Issue by toco** [hmatuschek/qdmr#245]
On c024348, verifying the example kw.yaml with an Anytone AT-D878UVII connected fails with the error:
> Expected reference to a group call digital contact.

<img width="1157" alt="Bildschirmfoto 2022-08-30 um 23 41 58" src="https://user-images.githubusercontent.com/272560/187548968-9093ec52-7da6-47c9-86af-dcad2eff999a.png">

Once I remove the "All Call" contact it passes.
This also blocks writing the config to the radio even when I have  "Ignore verification warnings" checked in the settings.

It worked fine with version 0.10.2-2.

**Comment by hmatuschek** [comment]
To my knowledge, a group list can only contain group calls. The only exception is the OpenGD77 firmware. It worked with previous versions because I missed to check that (see #238).
