### ISSUE TITLE
Missing link for reporting issues in manuals page

### ISSUE THREAD

**Issue by dforsi** [hmatuschek/qdmr#256]
The page at https://dm3mat.darc.de/qdmr/manual/re02.html doesn't render the web address for reporting issues.

This is the text visible at the end of the page:
> `If you stumble across one of them, consider opening an issue at <xlink></xlink>.`

And this is a screenshot:

![image](https://user-images.githubusercontent.com/1055635/193474837-97aca205-5207-4388-aa71-26247132247e.png)

**Comment by hmatuschek** [comment]
Fixed that in master, will be updated with the next release.
