### ISSUE TITLE
Open-GD77: Scanlist encoding and decoding fails

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#26]
The encoding and decoding of scan lists is totally off. Apparently the storage address of the scan lists appear to be wrong.

**Comment by DC7IA** [comment]
As mentioned in #27:

> The OpenGD77CPS does not have scan lists, since OpenGD77 does not support them:
> 
> > Scan Lists are not supported because Channel or Zone scan feature provides almost identical functionality.
> 
> https://github.com/rogerclarkmelbourne/OpenGD77/blob/master/docs/OpenGD77_User_Guide.md#codeplug-compatibility
> 
> Just remove it and done. :D
> 
 _Originally posted by @DC7IA in https://github.com/hmatuschek/qdmr/issues/27#issuecomment-752790025_

**Comment by hmatuschek** [comment]
Ok, disabled scan lists for OpenGD77 for now with 2e8082d79fbc308c93dc2b81076952f15d40c493.

**Comment by DC7IA** [comment]
How did you disable it? The menu is still visible. :thinking:

**Comment by hmatuschek** [comment]
Again, the settings are simply ignored. It is now just a feature the radio does not support like GPS.

**Comment by DC7IA** [comment]
Okay, thanks for the clarification. :D

**Comment by hmatuschek** [comment]
No problem. I know that it is hard to think that way if one is used to separate CPSs for each radio. Anyway, I need some sleep. Tomorrow, I'll release the bug fixes as binaries.
