### ISSUE TITLE
SegFault when trying to clone channel

### ISSUE THREAD

**Issue by greggawatt** [hmatuschek/qdmr#267]
Here is what I get from the terminal, any idea I can get better logs? Also I'd love to take a stab at fixing this with some help

`gigawatt@mesquite:~$ qdmr
Debug in src/application.cc@841: Set icon theme to 'light'.
Debug in src/application.cc@76: Search for translation in '/usr/share/locale/en_US/LC_MESSAGES'.
Debug in src/application.cc@76: Search for translation in '/usr/share/locale/en/LC_MESSAGES'.
Debug in src/repeaterbookcompleter.cc@326: Loaded repeater cache of 0 entries.
Debug in lib/userdatabase.cc@124: Loaded user database with 228681 entries from /home/gigawatt/.local/share/DM3MAT/qdmr/user.json.
Debug in lib/talkgroupdatabase.cc@140: Loaded talk group database with 1633 entries from /home/gigawatt/.local/share/DM3MAT/qdmr/talkgroups.json.
Debug in src/application.cc@132: Last known position: 
Debug in src/application.cc@184: Create main window using icon theme 'light'.
ERROR in lib/talkgroupdatabase.cc@72: Cannot download user database: Error transferring https://api.brandmeister.network/v1.0/groups/ - server replied: Not Found
Debug in src/application.cc@342: Load codeplug from '/home/gigawatt/anytone-codeplug2.yaml'.
Debug in lib/config.cc@349: Using format version 0.10.4.
Debug in lib/config.cc@398: Set default radio ID to 'K6XSS'.
Segmentation fault (core dumped)
`

**Comment by hmatuschek** [comment]
Thanks for reporting the issue, this crash has been fixed in 8cacdda70b6842b4d3fab343262e21fe8bc84433, but it is not released yet.

**Comment by greggawatt** [comment]
thank you! I'll await the next release, any timeline on that?

**Comment by hmatuschek** [comment]
Fixed with v0.11.0 release.
