### ISSUE TITLE
SEGFAULT when trying to write to radio

### ISSUE THREAD

**Issue by Janik-Haag** [hmatuschek/qdmr#275]
Envrionment:

RADIO: AT-D878UV2
QDMR: 0.11.0 built from source
Distro: nixos unstable

Building works just fine, im able to open qdmr, I can read the current code plug from the anytone.
But when trying to write to the radio I get a segfault, the terminal out put look like that

It seems like i'm able to write the contact list to the radio it, it atleast goes to 100% and the radio tells me its saving the data, but I cant find them in the contact list.

I also packaged qdmr for nixos https://github.com/NixOS/nixpkgs/pull/209733
But it's not yet merged and won't be until I can figureout why it segfaults 
```
Debug in lib/config.cc@372: Using format version 0.11.0.
Debug in lib/config.cc@423: Set default radio ID to 'My Radio'.
Debug in src/application.cc@441: Last device is invalid, search for new one.
Debug in lib/usbserial.cc@162: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@169: Found ttyACM1 (USB 28e9:18a).
Debug in lib/usbserial.cc@162: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@156: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM1 still exisist and has VID:PID 28e9:18a.
Debug in lib/radio.cc@55: Try to detect radio at Serial interface 'ttyACM1'.
Debug in lib/usbserial.cc@90: Try to open Serial interface 'ttyACM1'.
Debug in lib/usbserial.cc@124: Opened serial port ttyACM1 with 115200baud.
Debug in lib/anytone_interface.cc@307: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@336: Found radio 'D878UV2', version 'V100'.
Segmentation fault (core dumped)
```

**Comment by hmatuschek** [comment]
Ok, there might be several issues here. Let me disentangle them: 
 - First of all, I can confirm the crash when encoding the codeplug. This should be fixable.
 - The encoding of the call-sign DB might have changed. Which firmware version are you using?

**Comment by Janik-Haag** [comment]
Firmware version of the anytone is V3.01

**Comment by Janik-Haag** [comment]
I tried flashing it on Ubuntu with the official qdmr release and that worked (qdmr version is 0.10.2)

**Comment by Janik-Haag** [comment]
Can confirm that the patch fixed the issue :+1:
