### ISSUE TITLE
OpenGD77: Incorrect power levels

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#28]
OpenGD77 supports the power levels 50 mW, 250 mW, 500 mW, 750 mW, 1 W, 2 W, 3 W, 4 W and 5 W.

However, I can only choose `low` or `high`.

**Comment by DC7IA** [comment]
Writing changes the power level I use for hotspots from 50 mW to 5 W.

**Comment by hmatuschek** [comment]
OK, this is actually not a bug. With QDMR I try to provide a common code plug format that supports all radios. The idea is, to have a common exchangeable code-plug format. It is hard to assemble a proper code-plug for one region, to do that for every radio is simply impossible. To this end, I have to find some sort of a "largest common factor" of all radios. The majority of all radios supports only two or three power settings. Hence QDMR supports only two power levels. 

However, I am willing to extend the current options, if I find a reasonable way to map these options to all radios. I can imagine that a very low power-setting is desirable (e.g. 100mW or 50mW). E.g., for hotspots etc. 

How about "Minimum", "Low", "Mid", "High" and "Maximum" with the mapping

OpenGD77: Min=50mW, Low=1W, Mid=3W, High=5W, Max=5W
GD77/RD-5R: Min=1W, Low=1W, Mid=1W, High=5W, Max=5W
UV390: Min=1W, Low=1W, Mid=2.5W, High=5W, Max=5W
AnyTone: Min=1W, Low=1W, Mid=2.5W, High=5W, Max=7W

Anyway, decoding the power-setting and mapping them to one of the defined levels must be fixed for the OpenGD77 firmware.

**Comment by DC7IA** [comment]
>However, I am willing to extend the current options, if I find a reasonable way to map these options to all radios

Just convert it to the closes power level for other radios.

That way all possible values work and when flashing to other radios, a popup could inform the user that their radio does not support the level and that the closest will be chosen instead.

Includes all the values while keeping the compatibility, which I view as the most important feature of qdmr.

What do you think?

**Comment by hmatuschek** [comment]
I would no allow to select specific power levels. For some radios the output power depends on the band. E.g. Anytone devices may transmit with 7W on VHF but only max. 6W on UHF when set to maximum. Hence my suggestion to have labeled power levels.

**Comment by DC7IA** [comment]
Then maybe a level "lowest" for 50 mW?

I mean, I only really need 50 mW for the Hotspot and 5 W for everything else. :D

**Comment by hmatuschek** [comment]
Sure, here my TODO list

- [ ] Add "Min", "Mid" and "Max" power options to abstract code-plug representation.
- [ ] Fix CSV reader/writer
- [ ] Fix GUI. I.e. the channel editor
- [ ] Fix GD77 code-plug encoder/decoder
- [ ] Fix RD-5R code-plug encoder/decoder
- [ ] Fix OpenGD77 code-plug encoder/decoder
- [ ] Fix UV390 code-plug encoder/decoder
- [ ] Fix AT-D878UV codeplug encoder/decoder in d878uv branch

A lot to do.
