### ISSUE TITLE
Update AnyTone D878UV, D878UV II & D578UV codeplugs to FW version 3.01

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#287]
This ticket is a followup of issue #281. AnyTone released a new Firmware major revision 3.01 for the AT-D878UV and AT-D878UV II. The codeplug appears to be incompatible with firmware revisions 2.X. So it is (once again) time to update the AnyTone codeplugs. Because, it is so much fun to reverse engineer this huge and cluttered codeplug without any clue, what actually changed.

**Comment by nick-leroy** [comment]
Same for D578UV2

**Comment by hmatuschek** [comment]
This is work-in-progress with several other issues. I'll close that one now.
