### ISSUE TITLE
Unhandled device BTECH 'DMR-6X2UV'

### ISSUE THREAD

**Issue by cjoaquincruz** [hmatuschek/qdmr#288]
BTECH DMR-6X2UV is not recognized by qdmr Version 0.11.1 running on Ubuntu 20.04.5.  Output below:

Debug in lib/usbserial.cc@162: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@169: Found ttyACM0 (USB 28e9:18a).
Debug in lib/usbserial.cc@162: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@156: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM0 still exisist and has VID:PID 28e9:18a.
Debug in lib/radio.cc@55: Try to detect radio at Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@90: Try to open Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@124: Opened serial port ttyACM0 with 115200baud.
Debug in lib/anytone_interface.cc@307: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@336: Found radio 'D6X2UV', version 'V102'.
ERROR in lib/radio.cc@70: Unhandled device BTECH 'DMR-6X2UV'. Device known but not implemented yet.
Debug in lib/anytone_interface.cc@356: Anytone: Left program-mode.
Debug in lib/usbserial.cc@155: Serial port will close now.

**Comment by hmatuschek** [comment]
Already fixed in #277. Will be part of the 0.11.2 release.
