### ISSUE TITLE
GD-77 / OpenGD77: No GPS

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#29]
qdmr shows a GPS setting, but the GD-77 does not have GPS.

Maybe instead disable the setting to not cause confusion with users?

**Comment by hmatuschek** [comment]
Similar to the issue #28, I have to support all radios. QDMR does not know which radio gets programmed until the actual point where you load the code-plug to the device. Hence there is this verification step before uploading. When a radio does not support GPS, the GPS settings are simply ignored. I also cannot disable the GPS settings as the GUI is device independent. Again, QDMR shall become a universal code-plug editor.

**Comment by DC7IA** [comment]
Maybe just put a small info box saying `If your radio does not support GPS, this setting will be ignored.`

I mean... I literally tried to figure out how to enable GPS on my radio. :joy:

**Comment by hmatuschek** [comment]
True, I should note that somewhere.
