### ISSUE TITLE
Anytone 878: qdmr reports and sets *analog* mic gain, suggestion: change to *digital* mic gain

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#295]
The Anytone 878 has seperate settings for 

Menu->Settings->Voice Functions-> "DigiMic Level" vs. "AnaMic Level"

I think qdmr is reading and setting the "AnaMic Level" parameter with Settings -> Audio Settings -> MIC Amp.

I suggest changing this to reading and setting the "DigiMic Level" Parameter in the 878, since that parameter is more DMR-related?

**Comment by hmatuschek** [comment]
Ok, does it make more sense to set both entries or rather only touch dmr mic gain? The analog gain can then not be set at all. (Until I implement the anytone extension for the settings.)

**Comment by hmatuschek** [comment]
I just noticed, that I do not know the field, where the DMR mic amplification is stored. I've only got one called "Mic Gain" and that appears to be the FM mic gain. Maybe, this is one of the changes in the new firmware version 3.

**Comment by hmatuschek** [comment]
Fixed in the `anytone-settings-extension` branch. There is now a field allowing to set the FM mic gain separately. If not present, the DMR mic gain is used for the D878UV, D878UVII and D578UV. D868UVE and DMR-6X2UV do not have this option in the codeplug.
