### ISSUE TITLE
Channels are confusing without zone

### ISSUE THREAD

**Issue by fxkr** [hmatuschek/qdmr#299]
Often, a channel only makes sense in the context of a zone. On the actual radios, this is not a problem, as the zone name is usually displayed next to the channel name. But inside QDMR, the zone name is not displayed next to the channel name.

This can get confusing. Currently, the only way to keep track of what is what in the channel list in QDMR is to prefix the channel name with something like the zone name.

This is a problem, because many radios have limited display space. For example, channel names are max 16 chars in OpenGD77.

For example, if I add channels for all the repeaters in the [CARLA repeater network](https://www.carlaradio.net/) (K6LNK), I feel like I need to prefix the channel name with "K6LNK" or similar just so I won't confuse these channels with others. That leads to running out of space for the rest of the repeater name (e.g. "South Lake Tahoe" won't fit; best I can do is "SLTahoe"). This is unfortunate because it is such an unnecessary problem, as that prefix is entirely for QDMR - I can just add the channels to a zone, and the radio will then show the zone name next to it.

![image](https://user-images.githubusercontent.com/389616/216230873-97216627-3fad-4947-88ff-70a2431188a4.png)

I can think of two ways to improve the usability here, either:

1. Add a free text comment field that the QDMR user can use and that is not synced to the radio in any way, or
2. Add an auto-calculated, read-only column to the channels list that shows the zones that the channel is currently part of.

**Comment by hmatuschek** [comment]
Ok, implemented. If you like, you can test it in the `show-zones-in-channel-list` branch.

**Comment by fxkr** [comment]
Wow, that was fast! Tested. Thank you so much, this is exactly what I needed.

As an unexpected side benefit, it is now very obvious when there are channels that by accident aren't in any zone at all, and are thus unavailable in the radio..

**Comment by fxkr** [comment]
There seems to be a bug. The first channel in each zone has an empty Zones field.

This can be readily reproduced with a new codeplug for example by creating three channels, and a zone with all three.

![image](https://user-images.githubusercontent.com/389616/216439915-dfc93a13-b668-4f8d-8ada-fda3519880b1.png)
![image](https://user-images.githubusercontent.com/389616/216439987-1a61539a-b324-42e4-bb53-3a08f1fbb2a5.png)

**Comment by fxkr** [comment]
In [lib/configobject.cc](https://github.com/hmatuschek/qdmr/commit/e9136816d0780e79f3747462e67283e465ce2264#diff-fc4c3d51eb94be9ed088b2fac3c2491bf7201c3151017560c4ad85e5610eecf9), `return 0 < indexOf(obj)` should be `return 0 <= indexOf(obj)`.

**Comment by hmatuschek** [comment]
You are right, thanks.
