### ISSUE TITLE
Add support for OpenGD77 on TyT MD-UV380/UV390.

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#300]
There are some differences in the codeplug and/or memory regions, the codeplug is written to between the GD77/RD-5R and UV380/UV390 variants of OpenGD77. To this end, the variant detection must be implemeted first (issue #239).

**Comment by dd5xl** [comment]
This is also valid for OpenGD77 on Baofeng DM1701 / RT84: Contacts, RX groups and scan lists are corrupted, channels and zones seem to be OK.
USB VID/PID is indicated as 1FC9:0094

Please contact me if you need a valid OpenGD77 codeplug for these radios for comparison or analysis!
I would also support in testing any new implementation. I've set up a build environment to build qdmr directly out of the repo.

 73 de Bert DD5XL

**Comment by hmatuschek** [comment]
Created a single issue (#394) for all OpenGD77 related issues. I need to rewrite it anyway.
