### ISSUE TITLE
RT3S User Database won't work

### ISSUE THREAD

**Issue by vk1kcm** [hmatuschek/qdmr#303]
I'm using qDMR on a M1 Max MacBook Pro under macOS Ventura to program a Retevis RT3s using firmware 18.16.  Everything seems to work well except for the user database.  

Trying to install the user database gives the error "The detected radio 'TT MD-UV390' does support a call-sign DB. This feature, however, is not implemented yet."

**Comment by vk1kcm** [comment]
Actually I mentioned it as on the matrix it's listed as supported but untested.

**Comment by hmatuschek** [comment]
It was implemented, but I've disabled that feature for some reason. In the branch `disabled-tyt-callsign-db` it is now enabled. If it works for you, let me know. I can then merge it into mast and it will then be enabled with the next release.

**Comment by vk1kcm** [comment]
Thanks Hannes, that appears to work.  I just compiled up the branch and uploaded it twice, once with 10,000 entries and the second with 9,000 entries.  Both seemed to work fine.
It looks like it gives me callsign, name and country.  The other uploads give a town or locality as well, is that deliberate?
