### ISSUE TITLE
Problem with my code plug layout or other issue is causing incorrect contact/channel data

### ISSUE THREAD

**Issue by DougEubanks** [hmatuschek/qdmr#305]
I've verified my radio is working using the Anytone CPS.  Configuring the same data in qdmr leads to me transmitting with the incorrect contact ID of 12345678, when it should be 9998.

I don't know if I'm doing something specific in my code plug layout that is causing some corruption or if I've stumbled upon a bug.  I don't know if I'm overflowing a field, I like to use long/full descriptions in my zones/channels names like "PRN Hillsborough", even if the D578 can't scroll the full name yet.  I'll be happy to provide my code plug to you directly, but I'd prefer not to upload it since a lid may download it and not change the radio ID.  I am attaching screenshots to help illustrate the behavior I'm seeing.

![Code Plug Screenshot](https://user-images.githubusercontent.com/83023382/218126709-d34c7b9b-ee6a-4e98-9441-02d7db4d841e.png)
![Radio Display (Idle)](https://user-images.githubusercontent.com/83023382/218126714-ade821ef-8c8a-4648-a15f-9f8d8d585307.jpg)
![Radio Display (Transmitting)](https://user-images.githubusercontent.com/83023382/218126737-279e3531-5855-4441-86c2-f70f3a8fad63.jpg)

This is an Anytone D578 with the 1.17 firmware.

**Comment by DougEubanks** [comment]
I just did a READ from the radio to see if my data was making it over.  Strangely, my contacts were not being written and instead I only see Contact1, with an ID of 12345678.  I do have contacts configured in the Contacts tab.

![Contacts](https://user-images.githubusercontent.com/83023382/218128718-0b48e22b-e905-4764-a1b6-d5ed842d42a5.png)

**Comment by DougEubanks** [comment]
While troubleshooting, I did a read from the radio.  I'm getting this warning.
`Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.`

**Comment by DougEubanks** [comment]
Here is the debug from the application.
`Debug in src/application.cc@860: Set icon theme to 'dark'.
Debug in src/application.cc@77: Search for translation in '/usr/local/share/locale/en_US/LC_MESSAGES'.
Debug in src/application.cc@77: Search for translation in '/usr/local/share/locale/en/LC_MESSAGES'.
Debug in src/repeaterbookcompleter.cc@326: Loaded repeater cache of 0 entries.
Debug in lib/userdatabase.cc@124: Loaded user database with 232947 entries from /home/douge/.local/share/DM3MAT/qdmr/user.json.
Debug in lib/talkgroupdatabase.cc@140: Loaded talk group database with 1641 entries from /home/douge/.local/share/DM3MAT/qdmr/talkgroups.json.
Debug in src/application.cc@133: Last known position: 
Debug in src/application.cc@185: Create main window using icon theme 'dark'.
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
kf.coreaddons: Expected a KPluginFactory, got a KIOPluginForMetaData
kf.coreaddons: Expected a KPluginFactory, got a KIOPluginForMetaData
Debug in src/application.cc@347: Load codeplug from '/home/douge/NextCloud/Amateur Radio/D578.yaml'.
Debug in lib/config.cc@372: Using format version 0.11.2.
Debug in lib/config.cc@426: Set default radio ID to 'D578'.
Debug in src/application.cc@446: Last device is invalid, search for new one.
Debug in lib/usbserial.cc@162: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@169: Found ttyACM0 (USB 28e9:18a).
Debug in lib/usbserial.cc@162: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@156: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM0 still exisist and has VID:PID 28e9:18a.
Debug in lib/radio.cc@56: Try to detect radio at Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@90: Try to open Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@124: Opened serial port ttyACM0 with 115200baud.
Debug in lib/anytone_interface.cc@307: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@336: Found radio 'D578UV', version 'V110'.
Debug in lib/d878uv_codeplug.cc@2519: Allocate roaming zone at 1043000
Debug in lib/d878uv_codeplug.cc@2548: Encode roaming zone ROAM ZONE 1 (1) at 1043000 with 0 elements.
Debug in lib/anytone_interface.cc@356: Anytone: Left program-mode.
Debug in lib/usbserial.cc@155: Serial port will close now.
Debug in src/application.cc@736: Write complete.
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM0 still exisist and has VID:PID 28e9:18a.
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM0 still exisist and has VID:PID 28e9:18a.
Debug in lib/radio.cc@56: Try to detect radio at Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@90: Try to open Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@124: Opened serial port ttyACM0 with 115200baud.
Debug in lib/anytone_interface.cc@307: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@336: Found radio 'D578UV', version 'V110'.
Debug in lib/anytone_radio.cc@192: Download of 15 bitmaps.
Debug in lib/d878uv_codeplug.cc@2519: Allocate roaming zone at 1043000
Debug in lib/anytone_interface.cc@356: Anytone: Left program-mode.
Debug in lib/usbserial.cc@155: Serial port will close now.
Debug in lib/d868uv_codeplug.cc@1132: Store id 3137063 at idx 0.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Warning in lib/anytone_codeplug.cc@887: Unknown value 255 for alert type of AnyTone contact element. Maybe the codeplug implementation is outdated. Consider reporting it at https://github.com/hmatuschek/qdmr.
Info in lib/d878uv_codeplug.cc@1637: No matching APRS channel found for TX frequency 145MHz, create one as 'APRS Channel'
`

**Comment by hmatuschek** [comment]
This is likely an incompatibility issue with the current firmware. Could you check, which firmware are you running. Also which device is it exactly? I am currently working on the settings extension for the AnyTone devices. Once I've finished this, I'll focus on the update to the firmware revision 3.0. This however,  may take some time, as there are a myriad of settings to be checked.

**Comment by DougEubanks** [comment]
AT-D578UV PRO Version 1.17 (the latest)

**Comment by hmatuschek** [comment]
I've just checked the contact encoding using the latest CPS 1.17, and I found no changes in the encoding. If there is nothing secret in the codeplug, could you write one onto the device using the windows CPS and then read the binary codeplug from the device and send it to me. There might be another issue I cannot reproduce here. To read the binary codeplug from the device, use the command line tool shipped with qdmr:

```
dmrconf --read d578uv_codeplug.dfu
```
This will write the binary codeplug into the file named `d578uv_codeplug.dfu`. This will help me to understand the problem.

**Comment by DougEubanks** [comment]
Testing the latest dev build on Fedora 38 works as expected.
