### ISSUE TITLE
TYT UV-390 Squelch on DMR channels

### ISSUE THREAD

**Issue by adryd325** [hmatuschek/qdmr#307]
The TYT UV-390 and family use squelch on DMR channels. QDMR seems to reset the squelch every time when writing to the radio to zero. It would be nice if the squelch value was stored in tytExtension or something like that.

**Comment by adryd325** [comment]
If it helps, I tested with my radio: the squelch setting is at the same location in the codeplug for DMR channels and Analog channels

**Comment by hmatuschek** [comment]
Implemented it in the `tyt-squelch-on-dmr-channels` branch. I cannot test it right now, so it would be great if you could. If it works for you, I'll merge it into master.

**Comment by adryd325** [comment]
I just tested it and it works as expected, both reading from and writing to the radio. Thank you so much!
