### ISSUE TITLE
suggestion: Adding of channels to RX group as checklist

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#32]
If channels for RX group could be chosen as a checklist, adding many channels in a row became easier.

 Alternatively, maybe do it like this:

![grafik](https://user-images.githubusercontent.com/26351852/103388177-e2642400-4b07-11eb-9fb7-6090fb645add.png)

This has the advantage that you can just hit the button 20 times to add twenty channels in a row, making it much easier to add many consecutive channels at once.

Far easier than: Add Contact -> select contact -> OK

Saves two clicks. :) 

What do you think?

**Comment by DC7IA** [comment]
This is the only thing I like about the "original" software. Everything else is just painfully complicated. xD

**Comment by hmatuschek** [comment]
Sure, the same holds true for zones and scan lists.
