### ISSUE TITLE
Anytone Extensions: entry/display format of "groupCallHangTime" seems to be inconsistent?

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#325]
868 FW 2.40 here. 

I tried various formats for entering hold times. According to lib/anytone_extension.cc time should be in seconds? If I enter "5 s", qdmr displays "5 ms", "15 s" -> "5 ms", "50 s" -> "0", "5000 ms" -> "0"

 What is the correct way to enter the desired time here?

**Comment by hmatuschek** [comment]
True, is an issue with the changed regular expression syntax. The parser ignores every unit and interprets everything as ms. So 5000 should do. I'll fix it.

**Comment by hmatuschek** [comment]
Ok, should be fixed now.
