### ISSUE TITLE
Current anytone-branch writes garbled user DB to radio (config is ok again!)

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#328]
Just tested with my 868 with firmware 2.40: read the config from the radio and wrote it back without making any changes, 868 starts with "Program Error / Please Initialize The Radio! / Confirm" - then I am presented with the "Calibrate Date" screen as expected. What can I provide to debug that? Must have been introduced in the last weeks, the branch used to work.

No unexpected debug output:
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM3 still exisist and has VID:PID 28e9:18a.
Debug in lib/usbdevice.cc@247: Check if serial port ttyACM3 still exisist and has VID:PID 28e9:18a.
Debug in lib/radio.cc@56: Try to detect radio at Serial interface 'ttyACM3'.
Debug in lib/usbserial.cc@90: Try to open Serial interface 'ttyACM3'.
Debug in lib/usbserial.cc@124: Opened serial port ttyACM3 with 115200baud.
Debug in lib/anytone_interface.cc@307: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@336: Found radio 'D868UVE', version 'V102'.
Debug in lib/anytone_interface.cc@356: Anytone: Left program-mode.
Debug in lib/usbserial.cc@155: Serial port will close now.
Debug in src/application.cc@736: Write complete.

Will test with my 878 when I have a working second radio again, hold on.. :-)

**Comment by hmatuschek** [comment]
A separate issue is ok. The other one is purely for the extension module. Not bugs introduced with it. This one, however, will be hard to find. It would help to find the commit, that broke the 868.

**Comment by hmatuschek** [comment]
Ok, thanks. This helps a lot.

**Comment by hmatuschek** [comment]
Fixed in the `anytone-settings-extension` branch (where else). Turns out, the AnyTone devices do not like empty zones.
