### ISSUE TITLE
Improve compatibility with Arch Linux

### ISSUE THREAD

**Issue by Nimayer** [hmatuschek/qdmr#33]
Hi,
I'm trying to run qdmr on my Arch Linux installation, and I think there are two steps which can improve the compatibilty with this distribution

### Dependencies instructions
I managed to compile qdmr, after installing the dependencies with
```
sudo pacman -S qt5-tools qt5-serialport qt5-location
```
Could it be possible to add this command to the README for other Arch Linux users?

### Shared libraries path
Also after doing `make install`, qdmr complains about missing shared libraries.
I figured out that the issue is caused by libdmr being installed in `/usr/local/lib`

Arch linux does not use `/usr/local/lib` for its shared libraries, but uses `/usr/lib` instead ([source](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_etiquette))
I temporarily solved by moving the library objects to `/usr/lib` but it would be cool if the `make install` command could install the libraries in `/usr/lib` if an Arch Linux installation is detected.
An Arch Linux installation can be detected for example by reading `/etc/issue` and comparing with `Arch Linux \r (\l)`

Thank you!

**Comment by hmatuschek** [comment]
Thanks for the remarks. I'll update the readme accordingly. However, there are more packages needed to build QDMR: git, cmake & libusb. What are these package names under ARCH?

To install QDMR under the system path /usr/ call cmake with
```
cmake .. -DMAKE_INSTALL_PREFIX=/usr/
```
I'll also add this to the readme.

**Comment by Nimayer** [comment]
Hi @hmatuschek,
The Arch Linux packages for git, cmake and libusb are the omonimous `git` `cmake` and `libusb`
And I think `base-devel` is also needed to get GCC and other compiling tools
So the complete dependencies for Arch Linux should be
```
sudo pacman -S git base-devel cmake libusb qt5-tools qt5-serialport qt5-location
```

Thank you for fullfilling this request!
