### ISSUE TITLE
"save" dialog does not show codeplug files in the folder

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#34]
Not sure whether this is an issue with qdmr or not.

The "save" dialog does not show existing codeplug files:

![grafik](https://user-images.githubusercontent.com/26351852/103652832-f5da1980-4f63-11eb-9f8b-1cc4e4cb20d1.png)

The "open" dialog shows existing codeplug files:

![grafik](https://user-images.githubusercontent.com/26351852/103652781-e5c23a00-4f63-11eb-94d0-b06c1ddc9588.png)

The "open" dialog has a "Codeplug Files" filter, while the "save" dialog has a "CSV files" filter.

**Comment by hmatuschek** [comment]
Are you running the Snap image? The latter is quiet restricted out of the box. To gain access to the home directory, the "home" slot should be connected to the corresponding interface. This should happen automatically during install, but can be done manually with
```
$ sudo snap connect qdmr:home :home 
```

**Comment by DC7IA** [comment]
I'm using the .deb package from your PPA, since I couldn't get the snap version to work with the serial port for OpenGD77.

**Comment by hmatuschek** [comment]
Oh, yes that is a bug.

**Comment by hmatuschek** [comment]
By the way, my default file extension for the code-plug files is *.conf.
