### ISSUE TITLE
Anytone 878 extensions: channel/zone color setting mixed up - index off by two positions? Also: 868 has different key indexes..

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#340]
878 FW 3.01:
Setting "channelNameColor" does not seem to have any effect - it stays white as before. To get Channel B and the Zones in white, I have to set the color to "Turquoise".  Setting it to "White" gives, hm, probably orange?
Setting it to "Green" gives blue. Setting it to "Black" gives, yup, as expected, red. So the color is off by two positions?

Side note: key settings were not read from the radio, but are set correctly when set manually in qdmr. Just the naming of the buttons is something to get used to.. (as explained in https://github.com/hmatuschek/qdmr/issues/298#issuecomment-1568093684 )

Note to that note: on my 868 with FW 2.40, key settings indexes seem to be different - "Slot Set" is on position 36 on the 878, but  on position 35 on the 868. That is because on the 878, there is "Roaming" on position 33, which is not present on the 868. Also the 878 has more possible settings, but besides the "Roaming" setting, they were added at the end. Is there an easy way to take that into account? I do not know how many (non-converted, FW 2.40) 868 are still around..

(As discussed in https://github.com/hmatuschek/qdmr/issues/298#issuecomment-1412379909 : changing item order between models or firmware releases)

**Comment by hmatuschek** [comment]
Concerning the colors: I suspected, that I messed up the reverse engineering. Obviously, I did not. So I need to add a color-mapping, as the same colors are encoded differently between devices. 

Concerning the key functions: I did the same for those. (E.g., https://github.com/hmatuschek/qdmr/blob/5b6624632e012632a51a9889bb805efd58924bbb/lib/d878uv_codeplug.cc#L1545) However, there might be a mistake in there.

**Comment by hmatuschek** [comment]
The colors should be fixed in `fix-anytone-colors` branch. Will have a look at the key-functions now.

**Comment by hmatuschek** [comment]
Concerning the mic gain: This was a stupid mistake `min(1,min(10,gain))` will get you always 1.

**Comment by hmatuschek** [comment]
Ok, those colors should be fixed now.

**Comment by hmatuschek** [comment]
Key functions should be fixed now.
