### ISSUE TITLE
878 3.02n: "GPS mode" has more options in the radio than in the Windows CPS..

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#341]
Bonus feature in 3.02n: "GPS Mode" has GLONASS added, which can be selected in the radio. Thus gpsSettings -> mode drop down needs more options for the new modes. Since it is not in the changelog, it would be interesting whether it is only the menu option or indeed added support for GLONASS.

**Comment by hmatuschek** [comment]
Nice to be ahead to the manufacturer CPS.

**Comment by hmatuschek** [comment]
The 868 does not have the extended setting element that holds the GPS mode. So there is no such option for the 868.
