### ISSUE TITLE
Writing codeplug to Anytone AT-D878UVII Plus resets APRS frequencies on device.

### ISSUE THREAD

**Issue by toco** [hmatuschek/qdmr#349]
When uploading a code-plug to my Anytone AT-D878UVII Plus the APRS frequencies stored on the device get reset.

Reproduced with qdmr at https://github.com/hmatuschek/qdmr/commit/a335412e6c760300757a217a5dcbd5e94a0018f5 and Anytone firmware 3.02n (this also happened with 3.01 already).

**Comment by hmatuschek** [comment]
I need to update the APRS settings to the new FW versions anyway. Currently only one FM APRS frequency is supported.

**Comment by toco** [comment]
Yeah and even that no longer works (or maybe now override it which it didn't before). I also think the config concept in the UI with multiple channels with different source/destination settings doesn't map correctly to the AnyTone capabilities, which is just one source/destination config for FM, but multiple frequencies that can be selected.

**Comment by hmatuschek** [comment]
I do not understand the need for one APRS configuration but several frequencies. If any, I would suspect to need it the other way around. However, to map that to the concept of qdmr, I would rather add an extension to the one FM-APRS setting allowed for the anytone devices that will hold the additional frequencies.

**Comment by toco** [comment]
That sounds like a good way to do it.

**Comment by hmatuschek** [comment]
This fix requires some rewriting of the present codeplug elements dealing with the positioning settings. So expect some mayhem before it gets better.

**Comment by hmatuschek** [comment]
Does anyone know, what this "pass all" option means?

**Comment by toco** [comment]
Show all APRS message types AFAIK.

**Comment by hmatuschek** [comment]
Ok, thanks.

**Comment by toco** [comment]
Small correction: PASS ALL shows messages that failed CRC checks.

> Add new function in CPS->APRS-> Analog -> PASS ALL. Set On PASSALL will receive more APRS message, but some are with corrupted data.
> Default OFF. This command enables the attempt to display corrupted packets when PASSALL is ON. When PASSALL is OFF, packets will be displayed only if the CRC (error checking) is correct.

https://groups.io/g/ANYTONE-878/topic/90505161?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3A%2C%2C%2C0%2C0%2C0%2C90505161

**Comment by hmatuschek** [comment]
Ok, I was just puzzled, as this option is stored near the FM APRS transmission options. There is an separate memory region, where the FM APRS reception options are stored.

**Comment by hmatuschek** [comment]
Uh, that was a nasty one, smashed the stack a bit and got random crashes every where. Fortunately, there is valgrinds memcheck.

**Comment by hmatuschek** [comment]
Is there any means of selecting, which FM APRS frequency is used? I haven't found anything in the CPS.

**Comment by hmatuschek** [comment]
With the last commit, it is now possible to add and edit the additional FM APRS frequencies. There are only 7, the first is the default and is taken from the revert channel associated the the qdmr APRS system. There is now also a reference in the AnyTone FM and DMR channel extensions allowing to select the FM APRS frequency. If none is selected, the default (revert channel) is taken.

**Comment by hmatuschek** [comment]
I believe, this issue is now fixed. Just test the extension and let me know.

**Comment by toco** [comment]
I‘m out of country without my laptop. The Rasberry Pi I have with me runs into the Linux USB issue…
Can check next week.

**Comment by toco** [comment]
Copied over from the other issue, had the wrong window open:

> Tested on c457377. Things I noticed:

> 1. I added two APRS frequencies in the config, on the HT the first one appears twice, the second one appears in the second slot.
> 2. Report filters are always shown as "off" on device, even though I set some to "on".

**Comment by hmatuschek** [comment]
The second point should now be fixed now in this branch.

**Comment by toco** [comment]
> Concerning the first point: You can only define 7 additional FM APRS frequencies in the extension. The first frequency is set by the FM APRS system. That is, within the config:

Ah! With the explanation that makes sense.

**Comment by toco** [comment]
Looks like it works now, thanks for the very quick turnaround time!

The only thing I'm missing is setting (or not resetting) the selected APRS frequency.

Differences in binary codeplug read from device after changing the selected frequency:
```
diff <(xxd APRS_freq_1.dfu) <(xxd APRS_freq_2.dfu) 
187c187
< 00000ba0: 0000 0000 0000 2080 0040 0000 0000 0000  ...... ..@......
---
> 00000ba0: 0001 0000 0000 2080 0040 0000 0000 0000  ...... ..@......
2048c2048
< 00007ff0: 10d8 c869 59                             ...iY
---
> 00007ff0: 10a5 d9cf b8                             .....
```

```
diff <(xxd APRS_freq_1.dfu) <(xxd APRS_freq_3.dfu)            
187c187
< 00000ba0: 0000 0000 0000 2080 0040 0000 0000 0000  ...... ..@......
---
> 00000ba0: 0002 0000 0000 2080 0040 0000 0000 0000  ...... ..@......
2048c2048
< 00007ff0: 10d8 c869 59                             ...iY
---
> 00007ff0: 1063 ec54 41                             .c.TA
```

**Comment by hmatuschek** [comment]
The frequency can be set in the Anytone extension of the channel. There you can select the FM APRS frequency. However, selecting none will select the default one specified in the FM APRS system. So, only the additional frequencies are selectable.
