### ISSUE TITLE
Please add support for Baofeng DR-1801UV

### ISSUE THREAD

**Issue by Tijs-Powergrim** [hmatuschek/qdmr#359]
Hi, I was testing with QDMR, and I am unable to connect. Seems that my device just is not supported yet. It is a BAOFENG DR-1801UV. I am happy to help with all the information needed to get this device supported.

**Comment by Tijs-Powergrim** [comment]
I am running openSuse leap 15.4. I am probably very connect to the OBS HW repo. So therefore I got 0.11.1. I do see some activity for this issue on version 0.11.2. Is it possible to install that one with Zypper?

**Comment by hmatuschek** [comment]
I do not know, whether you mean the BF-1801UV A6 (relatively new device). This one is implemented in the `dr1801` branch and scheduled for the 0.12.0 release. It works, but there are still some bugs. For example, I can only write the codeplug with 9.6k, this takes ages. However, make sure, that this is your device. There is an older version with the same name and chassis.

**Comment by hmatuschek** [comment]
BTW, let me know, if it is the device mentioned in the issue #285. If so, this issue would then be a duplicate.

**Comment by Tijs-Powergrim** [comment]
Good afternoon, thanks, PD1TUX Tijs

Op do 20 jul. 2023 12:39 schreef Hannes Matuschek ***@***.***
