### ISSUE TITLE
message on radio when reading/writing

### ISSUE THREAD

**Issue by DC7IA** [hmatuschek/qdmr#36]
The radio displays "Write Codeplug" while it should display "Writing Codeplug", since that is what it is doing.
First time I saw "Write Codeplug", I thought it was asking me to confirm somehow.
Same for "Read Codeplug", which should be "Reading Codeplug".

Present Progressive, because it is still going on. :) 

Seems like a small change (it is!), but makes it less confusing.

Wanted to make a PR, but couldn't locate it in the code.

**Comment by hmatuschek** [comment]
It is in lib/opengd77_interface.cc. I cannot fix it right now, can do it tonight.
