### ISSUE TITLE
repeaterbook.com rate limiting

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#360]
I currently get the following response:

`You have made too many queries. Please slow down the rate in which queries are made. RepeaterBook Wiki Article: https://www.repeaterbook.com/wiki/doku.php?id=api&s[]=api#rate_limiting`

Indeed qdmr currently is sending a request for every typed character - also when for example editing the repeater name and adding some more description. Would it be a lot of work for example to add a "look up callsign" button for a repeaterbook query and only then send a request?

**Comment by hmatuschek** [comment]
First, I use now a regex to extract the call from the channel name. As the completer uses a cache, this should limit the requests send. I hope, this is enough. I cannot limit the amount of request per time-interval as repeaterbook will not tell me the limit.

**Comment by hmatuschek** [comment]
Did it work for you?
