### ISSUE TITLE
Loading plug from GD77 fails

### ISSUE THREAD

**Issue by OH1KH** [hmatuschek/qdmr#37]
HI !
This is very welcome!  CPS just stopped to start in my wine (Fedora32/W5.0) some time ago. I can run it on fresh Mint20 cinnamon in virtual box, so it must be some of wine settings or add on files missing from my old wine. True linux program is always best!

Just compiled qdmr. Easy. If you can compile wsjtx no additional packages are need for this. After adding new udev rule (had some GD77 rules at usb rule file before) it can find radio.
Also download works up to 100% but then it freezes.

Popup message:
Cannot decode code-plug: decode(): Cannot decode codeplug: Cannot link RX group list at index 0.

Last lines from console where I started it:
Debug in /home/saku/qdmr/lib/opengd77_codeplug.cc@487: Contact 979 enabled, mapped to index 974
Debug in /home/saku/qdmr/lib/opengd77_codeplug.cc@518: RX group list at index 1 mapped to 0
Debug in /home/saku/qdmr/lib/gd77_codeplug.cc@220: Cannot link RX group list 'Suomi: contact #4 is not defined.

From grayed window I can see that it has found my call, dmrid and intro texts ok.
It just cannot pass " link RX group list" at the end.

Perhaps it should ask permission to skip the broken part and continue with data it has received ok till that.

I would like to have current codeplug as base of fixes. It is too big job to rewrite all from beginning.

**Comment by hmatuschek** [comment]
Thanks for the information!
I do not own a GD77, hence I cannot test it and the current implementation is a "blind" one.
The issues you described, sound like an index error in my implementation of the decoding of the code-plug. These are particularly hard to find without testing. However, the download itself appears to work.

Could you do me a favor? If you complied everything from sources, you should have the command line tool as well. Could you download the binary image of the code-plug with the command line tool? Call
```
$ dmrconf read --verbose gd77_codeplug.dfu
```
This should download the image into a DFU file called "gd77_codeplug.dfu". You could then decode it to text (if it would work) with
```
$ dmrconf decode --radio=gd77 gd77_codeplug.dfu
```
this step should fail now, as it tries to decode the codeplug. However, if you send me the codeplug (to dm3mat@darc.de) or attach it to a comment here, I should be able to find the index error easily.

**Comment by hmatuschek** [comment]
Just a quick question: Are we talking about OpenGD77 or the original GD77 firmware?

**Comment by hmatuschek** [comment]
Ok, maybe there is indeed an issue with the code-plug programmed to the radio. I turned missing contacts in RX group lists into warnings. The decoding should continue there. 29a8e5fff61bd576a6675dafc4544ecd95dcd502

**Comment by OH1KH** [comment]
Good morning!

It is OpenGD77 radio. As guessed the decode failed:
[saku@hamtpad tmp]$  dmrconf decode --radio=opengd77 opengd77_codeplug.dfu
ERROR in /home/saku/qdmr/cli/decodecodeplug.cc@118: Cannot decode binary codeplug file 'opengd77_codeplug.dfu': decode(): Cannot decode codeplug: Cannot link RX group list at index 0.

Here is the downloaded codeplug.
[gd77dfu.zip](https://github.com/hmatuschek/qdmr/files/5824030/gd77dfu.zip)

I'll check your latest commit.

**Comment by OH1KH** [comment]
HI!
With the latest version I had error in first download around 49% complete:
ERROR in /home/saku/qdmr/lib/opengd77.cc@203: In download(), cannot read block 0:
	 Cannot read from device: Device returned error '-'

Second try went ok to 100% and now I can see lot of settings there. I do not know yet if there is something missing, but most of it seems to show up now.
I will continue testing...
Thank you !

**Comment by hmatuschek** [comment]
Thanks for the code-plug file. This helped a lot with the debugging. In fact, I found the issue: It appears that OpenGD77 uses a byte in each contact to store some additional information about the contact. In the original GD77 firmware, this byte was an indicator whether the contact is enabled or empty. Hence my code identified some contacts as "empty" even if they where not. For example contact "OH", "TG 91 WW" or "99 DMO SIMP". These contacts where then referenced in some RX group lists although being marked as "empty". This lead to the failure of the decoding. 

In commit ada0f3ac6c9c631d12e06fa203b8d6f0faa86a86, this is fixed.

I'll look now into the GUI issue.

**Comment by hmatuschek** [comment]
With commit 7b788b8c6c161d9a8ce89ec8cd769fef0ee3263e the GUI now adds a ".conf" extension if none is present or a "uncommon" one is used. Also the "load codeplug" dialog will now allow to load "any file".
