### ISSUE TITLE
Open Gd77 number of contacts

### ISSUE THREAD

**Issue by OH1KH** [hmatuschek/qdmr#38]
When verfying downloaded codeplug, or trying to upload it back to radio following error appears.

"Number of contacts 978 exceeds limit of 256."

Same downloaded codeplug used as in issue #37

**Comment by hmatuschek** [comment]
This appears to be a similar issue like #22 and #21. 

I've just copied the limits for OpenGD77 from the original GD77 firmware (probably an old version of it). They are: 

- 1024 channels, 
- 32 zones with up to 80 channels per zone.
- 256 contacts (DMR)
- 76 RX group lists with up to 32 contacts per group

I'll try to figure out the actual limits of OpenGD77 and fix it.

**Comment by hmatuschek** [comment]
Ok, I've found some information about the number of zones, contacts etc. I updated the limits to 

- 68 zones, of 80 channels each.
- 1024 contacts

the rest remains the same. 

Let me know if it works for you.

**Comment by OH1KH** [comment]
No error any more.
I think those values are correct fro OpenGD77.
I could make verify and even dared to try upload that wnt through and it seem that contents are there still. (uploaded same plugin that was downloaded first)
I think this can be closed now (what comes to OpenGD77)

**Comment by hmatuschek** [comment]
OK, thanks for testing it out.
