### ISSUE TITLE
Error when writing Anytone codeplug with current github version (gd73 branch)

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#383]
Good morning,
please refer to attached screenshot, trying to write to my 878 with the current gd73 branch:
![anytone](https://github.com/hmatuschek/qdmr/assets/123975169/85e6ca1a-bc97-424b-9075-77137154d54f)

**Comment by hmatuschek** [comment]
This is actually a bug in the devel-branch. Should be easy to fix.

**Comment by hmatuschek** [comment]
Ok, should be fixed now.

**Comment by hmatuschek** [comment]
Opened a new issue for that #385, close that one.
