### ISSUE TITLE
Low prio: error message for too many contacts in RX group is misleading?

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#387]
A RX group (via "Group Lists") for the Anytone can hold 64 entries. When adding more, qdmr complains

"List 'contacts' takes at most 1 elements, 67 elements found."

Should it not say "takes at most 64 elements"?

**Comment by hmatuschek** [comment]
Should be fixed.

**Comment by hmatuschek** [comment]
Should be fixed now.
