### ISSUE TITLE
Devel/0.12.0 does not write CTCSS values for FM channel to Anytone 878

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#399]
Just a quick reminder for myself to supply more details later:

Current devel branch (actually branch 397..) does not write CTCSS values for an FM channel to my Anytone 878. Somewhat current master (0.11.3) works as expected. *Reading* from a radio with configured CTCSS works with "devel", the values are correctly displayed in the channel config. Writing and then reading again makes them disappear, though.

I will try to pinpoint when exactly writing CTCSS to Anytone 878 stopped working, but have to postpone that.

**Comment by hmatuschek** [comment]
You don't need to search for that: Copying instances of the Signaling enum
fails. The new intermediate representation needs a copy of the codeplug to
operate on. During this copying steps, the CTCSS setting is lost.

allesand ***@***.***> schrieb am Mi., 18. Okt. 2023, 13:43:
