### ISSUE TITLE
Low priority: implement "SMS templates" / "Quick SMS" edit for Anytone and GD-73

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#413]
At least the Anytone devices and the Radioddity GD-73 have "Quick SMS" (or called similar) with predefined SMS texts. The content can be configured in the Windows CPS, but not yet in qdmr.

**Comment by hmatuschek** [comment]
Here is the associated todo list:

- [x]  define SMS extension to hold templates and SMS settings (e.g., format)
- Implement encoding/decoding for all devices
  - [ ] AT-D868UVE
  - [ ] AT-D878UV
  - [ ] AT-D878UVII
  - [ ] AT-D578UV
  - [x] MD-399
  - [x] MD-UV390
  - [x] MD-2017
  - [x] DM-1701  
  - [ ] RD-5R
  - [ ] GD77
  - [x] GD73 
  - [x] DR-1801UV (A6)

**Comment by hmatuschek** [comment]
> Quick test: qdmr reads the quick sms ok, I can add a new one, but after writing to the radio, the quick sms list is empty in the radio. Will cross check with the windows CPS and report.

For what radio?
