### ISSUE TITLE
RT3/MD380 with md380tools has more button settings

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#419]
A RT3/MD380 with installed md380tools has more options for the side buttons that QDMR currently can not decode and thus can not write back to the radio.

For example:
- Direct talkgroup input
- Promiscuous mode on/off

This note as a reminder, will provide more info when at the laptop next time.. 

ERROR in src/extensionwrapper.cc@572: Cannot map value 81 to enum ButtonAction. Ignore attribute but this points to an incompatibility in some codeplug. Consider reporting it to https://github.com/hmatuschek/qdmr/issues.
ERROR in src/extensionwrapper.cc@572: Cannot map value 86 to enum ButtonAction. Ignore attribute but this points to an incompatibility in some codeplug. Consider reporting it to https://github.com/hmatuschek/qdmr/issues.

Tried 

*** tyt_extensions.hh.orig      2024-03-18 16:51:10.242894738 +0100
--- tyt_extensions.hh   2024-03-18 17:23:18.993810701 +0100
***************
*** 308,314 ****
      SwitchUpDown = 47,                  ///< Switch Channel A/B.
      RightKey = 48,                      ///< Who knows?
      LeftKey = 49,                       ///< Who knows?
!     ZoneDecrement = 55                  ///< Switch to previous zone.
    };
    Q_ENUM(ButtonAction)
  
--- 308,316 ----
      SwitchUpDown = 47,                  ///< Switch Channel A/B.
      RightKey = 48,                      ///< Who knows?
      LeftKey = 49,                       ///< Who knows?
!     ZoneDecrement = 55,                 ///< Switch to previous zone.
!     SetTalkgroup = 81,                        ///< md380tools: set temp. TG
!     PromiscOnOff = 86                 ///< md380tools: enable/disable promiscuous mode
    };
    Q_ENUM(ButtonAction)
  

but that does not seem to be enough.
@hmatuschek : what information do you need and/or what files do I need to change and send you a diff with the additional settings for an md380tools enabled RT3?

**Comment by hmatuschek** [comment]
Is there a dedicated CPS for md380tools? Or can these buttons only be set on the radio itself? If so, I may only need the information, you already provided above. For now, I do not know how I could detect the md380tools firmware.

**Comment by hmatuschek** [comment]
The changes you proposed above, should have been enough.

**Comment by hmatuschek** [comment]
Let me outline the changes needed:

- [x] Add new button functions to TyT extension.
- [ ] Find and implement ways to detect the presence of modified FW.
- Filter button functions by device and FW variant:
  - [ ] TyT MD-380, MD-390, Retevis RT 8
  - [ ] TyT MD-UV380, MD-UV390, Retvis RT 3S
  - [ ] MD380-Tools
