### ISSUE TITLE
"Ignore" scanlist error, can't upload

### ISSUE THREAD

**Issue by jeffrizzo** [hmatuschek/qdmr#42]
Not sure this is the appropriate place for this; would happily be redirected elsewhere.

I was thrilled to find QDMR - not needing Windows is my goal for all things radio.  :)

Using the latest (0.5.2) on MacOS 10.15.7 ("Catalina"), I was able to download from my RD-5R successfully.  However, after making some changes, I was unable to upload back to the radio.  "Detect" reported "Found device 'Baofeng/Radioddity RD-5R'.", but when I try to "upload", I got a message about my two scanlists not having a priority channel set.  Not knowing what this was, I chose "Ignore", but then the upload failed, timing out after about 1 minute without having uploaded anything and showing this error: "Cannot upload codeplug or user DB to device. An error occurred during upload: run: Cannot upload codeplug: hid_send_recv(): HID IO error: Exceeded max. retry count."

If I edit the scanlists to add priority channels (which I don't entirely understand, I actually am no longer using scanlists at all), the upload works.

**Comment by hmatuschek** [comment]
There appears to be a timing issue. That is, if there are several seconds between the message and clicking "ignore", the RD-5R appears to reset the connection and the upload fails. 

The warning is "needed" as the scan list will not work if it has no priority channel (appears to be a bug in the firmware). So if you do not use the scan list, just delete the list and the warning will disappear. Or (as you did) add a priority channel.

BTW, if you delete the scan lists, they will be removed from all channels referencing them.
