### ISSUE TITLE
Anytone 878: support for DTMF contacts needs improvement - currently IDs get deleted von write

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#425]
DTMF contacts are read correctly from the radio, the names are written back, but not the IDs, thus after write the DTMF contacts are not working anymore. 

Request: either write back nothing and all or improve DTMF contact support so the IDs do not get deleted on write.

Workaround: use the Windows CPS and CSV import/export of the analog address book 

Use case for DTMF contacts: switch talkgroups in SVXLink based FM networks - Anytone can not store "#" in the contacts but it works anyway

**Comment by hmatuschek** [comment]
Are numbers read correctly?

**Comment by hmatuschek** [comment]
Ok, fixed encoding of DTMF number length in branch `
425-fix-anytone-878-dtmf-contacts `.

**Comment by hmatuschek** [comment]
Fixed that too.
