### ISSUE TITLE
libusb - arm64 conflict

### ISSUE THREAD

**Issue by tkheard** [hmatuschek/qdmr#428]
I think this might not *really* be a qdmr problem.
Using macport, I attempted to install qdmr on my M1 Macbook running Sonoma 14.4.1, resulting in:

Error: Cannot install qdmr for the arch 'arm64' because
Error: its dependency libusb is only installed for the arch 'i386'
Error: and the configured universal_archs 'x86_64 i386' are not sufficient.
Error: Unable to execute port qdmr: architecture mismatch

Any suggestions?

**Comment by hmatuschek** [comment]
It is not and there is an open issue over at MacPorts (https://trac.macports.org/ticket/69852).
