### ISSUE TITLE
Current "devel": wrong frequency when importing .conf files from qdmr 0.8.1

### ISSUE THREAD

**Issue by allesand** [hmatuschek/qdmr#429]
Current "master" branch imports a .conf file from qdmr 0.8.1 ok, frequency in channel is

430.20000

Current "devel" branch imports .conf from 0.8.1 with frequencies in the channels like

430200000 MHz

(I am using qdmr 0.8.1 for my RD-5R with OpenGD77 due to the 16/32 RX TG group issue (described in #394) - so I can just use current master for the time being)

**Comment by hmatuschek** [comment]
Should be fixed in `429-wrong-frequency-when-importing-conf`.

**Comment by hmatuschek** [comment]
Merged in `devel`.
