### ISSUE TITLE
repeaterbook.com autocomplete doesn't work in North America

### ISSUE THREAD

**Issue by jancona** [hmatuschek/qdmr#445]
I'm in the US and the Repeaterbook autocomplete doesn't work for me. Evidently the repeaterbook.com database is segmented between US, Canada, Mexico and the rest of the world. It appears that QDMR is using the `https://www.repeaterbook.com/api/exportROW.php` endpoint, where ROW stands for "rest of world." For North America, "https://www.repeaterbook.com/api/export.php?callsign=KS1R" works. 

It appears the only US, Canada and Mexico are in the separate database. Caribbean and Central American countries are in the ROW database. So you might be able to use the callsign prefix to choose the endpoint, but a checkbox in Settings might be easier.

**Comment by hmatuschek** [comment]
Uh, that is annoying. Okay, implemented it via the settings dialog. So you can now select the region there. If you want to test it, checkout the branch referenced to the right `445-repeaterbookcom-autocomplete-doesnt-work-in-north-america`.

**Comment by hmatuschek** [comment]
Tested it here, appears to work. But boy, is the NA interface slow.

**Comment by hmatuschek** [comment]
FYI: I've already merged these changes into the `master` branch, if you want to test it.

**Comment by jancona** [comment]
Sorry for the delay, I just got around to testing this on the master branch and it works fine. Thanks!
