### ISSUE TITLE
CTCSS tone 177.3Hz is missed

### ISSUE THREAD

**Issue by pro100Roman** [hmatuschek/qdmr#446]
CTCSS tone 177.3Hz is missed

**Comment by hmatuschek** [comment]
There are many somewhat standard and non-standard tones missing. Also, some radios like the AnyTone ones allow for custom CTCSS frequencies. To this end, I would rather rework this subtone implementation instead of adding tones by hand.

**Comment by hmatuschek** [comment]
Moved to issue #455
