### ISSUE TITLE
SegFault writing to 878UVII+

### ISSUE THREAD

**Issue by PeterSprague** [hmatuschek/qdmr#482]
Something in my latest codeplugs causes QDMR to seg fault again when trying to write to the radio.  On a fresh source build from master.

Using dmrconf to isolate and display errors:
$ dmrconf write AnyTone_D878UVII+_Sept-28-2024-0924_seg-fault-fixes.yaml
Warning in cli/writecodeplug.cc@60: Verification Issue: Warn: In : The support for this radio is still under development. Some features may sill be missing or are not well tested.
[========================                          ] 49%
FATAL in lib/dfufile.cc@665: Cannot resolve offset 1640640h.

Comparing the last know working codeplug.yaml to latest with seg fault doesn't show anything that pops out to my untrained eyes.

[AnyTone_D878UVII+_Sept-29-2024-1315_seg-fault-fixes.txt](https://github.com/user-attachments/files/17181320/AnyTone_D878UVII%2B_Sept-29-2024-1315_seg-fault-fixes.txt)
[AnyTone_D878UVII+_Sept-26-2024-0858_uploads.txt](https://github.com/user-attachments/files/17181321/AnyTone_D878UVII%2B_Sept-26-2024-0858_uploads.txt)

**Comment by hmatuschek** [comment]
Can reproduce it:

- AnyTone_D878UVII+_Sept-29-2024-1315_seg-fault-fixes.txt -- crashes (too many SMS, there can only be 100).
- AnyTone_D878UVII+_Sept-26-2024-0858_uploads.txt -- encodes okay
- AnyTone_D878UVII+_Sept-26-2024-0927_seg_fault.txt -- also encodes okay. Can you give more details on that issue?

What I did using `dmrconf` as I do not own a D878UVII+:
```
dmrconf --verbose encode --radio=d878uv2 AnyTone_D878UVII+_Sept-26-2024-0927_seg_fault.txt test.dfu
```
This tries to encode the given YAML codeplug into a binary one that can be written to the device (codeplug format is the one for the D878UVII). If there is an encoding issue, this should trigger it.

I've created a new branch to fix this issue, so for testing it use the branch [`482-segfault-writing-too-many-sms`](https://github.com/hmatuschek/qdmr/tree/482-segfault-writing-too-many-sms).

**Comment by hmatuschek** [comment]
Should be fixed in [482-segfault-writing-too-many-sms](https://github.com/hmatuschek/qdmr/tree/482-segfault-writing-too-many-sms).

**Comment by f4inu** [comment]
@hmatuschek, is it possible to release v0.12.1 for this issue?
Thanks!
