### ISSUE TITLE
QDMR crash with Segmentation fault (core dumped) reading Amytone 878UVplus FW v.3.01

### ISSUE THREAD

**Issue by iu2omt** [hmatuschek/qdmr#491]
QDMR crash with Segmentation fault (core dumped) reading Amytone 878UVplus FW v.3.01 

qdmr
Debug in src/application.cc@1002: Set icon theme to 'light'.
Debug in src/application.cc@81: Search for translation in '/usr/local/share/locale/en_US/LC_MESSAGES'.
Debug in src/application.cc@84: Installed translator for locale 'en_US'.
Info in src/repeaterbookcompleter.cc@305: Cannot open repeater cache '/home/paolo/.local/share/DM3MAT/qdmr/repeaterbook.cache.json'.
Debug in lib/userdatabase.cc@132: Loaded user database with 270257 entries from /home/paolo/.local/share/DM3MAT/qdmr/user.json.
Debug in lib/talkgroupdatabase.cc@140: Loaded talk group database with 1680 entries from /home/paolo/.local/share/DM3MAT/qdmr/talkgroups.json.
Debug in src/application.cc@137: Last known position: 
Debug in src/application.cc@189: Create main window using icon theme 'light'.
Debug in src/application.cc@554: Last device is invalid, search for new one.
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 28e9:18a.
Debug in lib/usbserial.cc@124: Found ttyACM0 (USB 28e9:18a).
Debug in lib/usbserial.cc@117: Search for serial port with matching VID:PID 1fc9:94.
Debug in lib/hid_libusb.cc@128: Search for HID interfaces matching VID:PID 15a2:73.
Debug in lib/dfu_libusb.cc@157: Search for DFU devices matching VID:PID 483:df11.
Debug in lib/c7000device.cc@236: Search for C7000 devices matching VID:PID 1206:227.
Debug in lib/usbdevice.cc@258: Check if serial port ttyACM0 still exisist and has VID:PID 28e9:18a.
Debug in lib/radio.cc@61: Try to detect radio at Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@27: Try to open Serial interface 'ttyACM0'.
Debug in lib/usbserial.cc@72: Opened serial port ttyACM0 with 115200baud.
Debug in lib/anytone_interface.cc@308: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@337: Found radio 'D878UV', version 'V100'.
Debug in lib/anytone_radio.cc@200: Download of 15 bitmaps.
Debug in lib/d878uv_codeplug.cc@3749: Allocate roaming zone at 1043000
Debug in lib/anytone_interface.cc@357: Anytone: Left program-mode.
Debug in lib/usbserial.cc@105: Serial port will close now.
FATAL in lib/dfufile.cc@665: Cannot resolve offset 2180800h.
Segmentation fault (core dumped)

**Comment by iu2omt** [comment]
Sorry, 
I provide wrong FW info
radio is running FW 3.01

just update the post
thanks.

**Comment by hmatuschek** [comment]
There was a decoding issue (#482) with all AnyTone devices that will be fixed in the next release. Can you check, if the master branch still has this issue? It might be another problem.

**Comment by iu2omt** [comment]
hi,
i did the test with master (just cloned)

crash seems solved, but download code plug is empty.

see attached the log and a pop up rised at the end of download.
[qdm-master.log](https://github.com/user-attachments/files/17780659/qdm-master.log)
![Screenshot_2024-11-15_20-43-13](https://github.com/user-attachments/assets/db95e3e5-625c-46e5-a625-b791b71504ff)

**Comment by iu2omt** [comment]
aaditional note: DMRCONFIG build from latest master is working fine

**Comment by hmatuschek** [comment]
Sorry for the late reply. I am currently working on the OpenGD77 support for the 0.12.1 release. But I can include a hotfix for your issue in the next release. A proper update of the AnyTone support for the latest release will be scheduled for the 0.12.2 release. 

Can you attach the binary codeplug read from the device? E.g., by running 
```
dmrconf read codeplug_d878uv.dfu
``` 
and attach it here? This will help me reproducing the issue.

**Comment by iu2omt** [comment]
Hi Hannes,
just pull latest master and it works fine:
* ddeb812 - (HEAD -> master, origin/master, origin/HEAD, origin/505-prepare-0121-release) Re-implemented OpenGD77 channel extension. (#504) (11 hours ago) <Hannes Matuschek>

I roll back to
 * 60440ed - (HEAD) Enforces limit on SMS messages. Also added regression test. Addresses #482. (#484) (3 months ago) <Hannes Matuschek>
* 57282f7 - Update AnyTone APRS settings (#474) (3 months ago) <Hannes Matuschek>
and it still working fine

Instead rolling back to
* ebd6b72 - (HEAD, tag: v0.12.0) Update translations for 0.12.0 release (#456) (5 months ago) <Hannes Matuschek>
*   49c829f - Merge branch 'master' into devel (5 months ago) <Hannes Matuschek>
I'm getting the crash
 Debug in lib/anytone_interface.cc@308: Anytone: In program-mode now.
Debug in lib/anytone_interface.cc@337: Found radio 'D878UV', version 'V100'.
Debug in lib/anytone_radio.cc@200: Download of 15 bitmaps.
Debug in lib/d878uv_codeplug.cc@3749: Allocate roaming zone at 1043000
Debug in lib/anytone_interface.cc@357: Anytone: Left program-mode.
Debug in lib/usbserial.cc@105: Serial port will close now.
FATAL in lib/dfufile.cc@665: Cannot resolve offset 2180800h.
Segmentation fault (core dumped)

Sorry last time I was wrong with checkout ....
Issue for me is RESOLVED by  
60440ed - (HEAD) Enforces limit on SMS messages. Also added regression test. Addresses #482. (#484) (3 months ago) <Hannes Matuschek>
you can close it.

Thanks a lot

merry Christ Mass an happy new year

some attachments with logs
[note-hash_60440ed_fix#482_itworks.txt](https://github.com/user-attachments/files/18228361/note-hash_60440ed_fix.482_itworks.txt)
[note-hash_ddeb812_worksfine.txt](https://github.com/user-attachments/files/18228362/note-hash_ddeb812_worksfine.txt)
[note-hash_ebd6b72_log_crash.txt](https://github.com/user-attachments/files/18228363/note-hash_ebd6b72_log_crash.txt)

best regards
73 IU2OMT paolo

PS
I'm getting :
Warning in lib/anytone_codeplug.cc@726: Cannot decode admit cirit. 'same CC', use 'different CC' instead.
may be my CP has something wrong. any suggestion?

**Comment by hmatuschek** [comment]
Thanks for testing and letting me know. 

If I understood it correctly, you actually want to allow transmission if either the channel is free or used by a transmission with a different color code. This way, you know, that the other transmission is an interference targeting a (likely very distant) repeater. I've written some notes on the admit criterion (as far as I understood it) here:

https://github.com/hmatuschek/qdmr/discussions/506
