### ISSUE TITLE
Rework repeater database sources

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#494]
Repeater book is a really bad source. They have a very restrictive usage policy while relying on the community to keep their *product* up to date. I believe, that a reliable, community-driven repeater database with a liberal usage policy is a basic infrastructure that we all benefit from. Maybe someone at the large HAM clubs (ARRL, RSGB, DARC, ...) feels responsible to provide such a platform. Anyway, I need a replacement for the repeater book source. I'll switch back to 

  * https://repeatermap.de
  * https://hearham.com/repeaters

**Comment by jancona** [comment]
Yeah, the Repeaterbook API is broken right now too. ARRL says it gets its data from RFinder, but they're in flux right now--most of their assets, apparently including the directory, have been sold to a new company Unified Radios. The directory is online here: https://directory.unifiedradios.com/ but Rfinder's directory wasn't free and I doubt this one will be for long. 

Despite RepeaterBook's shortcomings, Garrett seems like a nice guy, and I don't think the [terms](https://www.repeaterbook.com/wiki/doku.php?id=api) are too bad. Are you planning on removing it as a source, or just adding others?

**Comment by jancona** [comment]
One additional source to consider is RadioID, although it's only DMR repeaters. See: https://radioid.net/database/dumps. [rptrs.json](https://radioid.net/static/rptrs.json) is their entire repeater database and [map.json](https://radioid.net/static/map.json) is the subset that includes lat/lon coordinates. One downside is that they include quite a few repeaters that aren't on the air, but data quality is an issue with all the sources I've seen.

**Comment by hmatuschek** [comment]
Okay, thanks for the info. I've added these sources (hearham is disabled for now, but can be enabled in the settings dialog). I kept repeaterbook but there is a server issue for non-US repeaters. You can test it in the branch https://github.com/hmatuschek/qdmr/tree/494-rework-repeater-database-sources.

**Comment by jancona** [comment]
It works for me! (I didn't test Repeaterbook's rest-of-world database because I know the endpoint is down.) One minor glitch: If I select or unselect sources in Settings, the changes don't seem to take effect until I restart, at least for the non-Repeaterbook sources. Perhaps this is because you cache them at start-up?
