### ISSUE TITLE
Cannot download codeplug from 878UV

### ISSUE THREAD

**Issue by hexagonal-sun** [hmatuschek/qdmr#50]
Hi,

I'm trying to download a codeplug from a new 878 radio and I'm having issues.  When downloading, I'm seeing a dialog that says:

`Cannot download codeplug from device. An error occurred during download:download Cannot download codeplug: Anytone: Cannot read data from device: No response from device: Timeout`

Running the command line yields:

```
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QObject::connect: Cannot queue arguments of type 'QSerialPort::SerialPortError'
(Make sure 'QSerialPort::SerialPortError' is registered using qRegisterMetaType().)
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
```

I'm running on MacOS 11.2.3.  I can download the codeplug with `dmrconfig` but I do experiance some courruption with the contacts TG list.

**Comment by hmatuschek** [comment]
It might be a stupid question, but have you turned down the volume pot to the minimum? There appears to be an issue with the connection where there is audio output while accessing the radio. This should lead to intermittent connections, sometimes it works sometimes not.

**Comment by hmatuschek** [comment]
Oh, wait. I can reproduce that problem here under MacOS 11.2.2. So there appears to be a real issue with MacOS and the serial port.

**Comment by hexagonal-sun** [comment]
@hmatuschek Thanks for the quick response!  Glad you could reproduce.

If you need me to test any candidate fixes my end, please let me know.

Thanks,
Matt (M0MLQ)

**Comment by hmatuschek** [comment]
Are able to compile qdmr from sources? If so, you may use the command line tool for now. It works nicely. It is called dmrconf and is installed along with qdmr. I just do not distribute it along with the app package.

**Comment by hexagonal-sun** [comment]
@hmatuschek Yep, I've got the compiled version and can confirm that `dmrconf` works great.  I'll use that as an interim solution.  Thanks!

**Comment by hmatuschek** [comment]
Just try the current master branch, it should work now.

**Comment by hexagonal-sun** [comment]
Just given this a try and it all works on my end.  Thanks for fixing so quickly.

I'll start using qdmr as my main programming software for the D878UV.  If I run into any more problems, I'll let you know.
