### ISSUE TITLE
Duplicate SMS templates keep getting added

### ISSUE THREAD

**Issue by ikbenkous** [hmatuschek/qdmr#511]
I don't know where these came from. But it seems to happens during loading and saving because I didn't change anything and it just appeared.

All of them have the "Hello!" "Welcome!" "Thank you!" "Good bye!" "Happy every day!" messages.

This is probably the work of multiple loads/saves.

(btw: is "Happy every day!" a reference to "pls rember"? lmao)
![image](https://github.com/user-attachments/assets/86e81065-17e7-4538-a245-a7174844b424)

**Comment by hmatuschek** [comment]
Uh, good to know. Seems like a missing `clear()` call. One moment please...
