### ISSUE TITLE
Typo in UI "qdrm"/"qdmr"

### ISSUE THREAD

**Issue by ikbenkous** [hmatuschek/qdmr#512]
Stumbled into this while translating.

https://github.com/hmatuschek/qdmr/blob/a2b547d517ec2de927b52f43e1c7b99582745b06/src/aboutdialog.ui#L14

**Comment by hmatuschek** [comment]
Thanks for spotting this one. Fixed in branch associated with #505.

**Comment by ikbenkous** [comment]
It seems the wrong `aboutdialog.ui` file was "fixed"?

https://github.com/hmatuschek/qdmr/blob/a85491f75f99a1ff2a0250e70bc80442b42915ed/src/aboutdialog.ui#L14
