### ISSUE TITLE
OpenGD77 incorrect zone reading.

### ISSUE THREAD

**Issue by ua0lnj** [hmatuschek/qdmr#522]
In each zone the first channel is skipped, the last channel is the first channel from the next zone.

**Comment by hmatuschek** [comment]
Nice off-by-one you found there. I'll check that.

**Comment by hmatuschek** [comment]
Should be fixed in the `522-opengd77-incorrect-zone-reading`.

**Comment by ua0lnj** [comment]
Yes, it works fine now!
