### ISSUE TITLE
Writing codeplug with option still selected leads to flashing old value

### ISSUE THREAD

**Issue by ikbenkous** [hmatuschek/qdmr#526]
When adjusting options in the extensions area on the right of the main settings tab, if you press the "write codeplug to radio" button with the state of the UI like it is in the image below, _it will flash the old value to the radio_.

This happens with the anytone extension in the `funcKey1Long` field but I have a strong gut feeling it's gonna copy straight over to other radios/extensions/fields just fine, lol.

![image](https://github.com/user-attachments/assets/8b2bc85b-13d7-42c8-b35d-2efa339ff4f7)

**Comment by hmatuschek** [comment]
Will work on it in the same branch as #520.
