### ISSUE TITLE
Inconsistent tooltip Intro Lines

### ISSUE THREAD

**Issue by obi134** [hmatuschek/qdmr#61]
Version 0.6.2 on Ubuntu

Intro Line 1 is showing a tooltip near mouse cursor. (mainwindow.ui, line 129 `<property name="toolTip">`)
Intro Line 2 is showing a tooltip on the bottom of the window. (mainwindow.ui, line 146 `<property name="statusTip">`)

This is inconsistent and should be aligned

**Comment by hmatuschek** [comment]
Just released version 0.6.3 fixing this and other things.
