### ISSUE TITLE
Multiple selection in all lists for delete and moving stuff around.

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#76]
Just add multiple selection for all lists.

**Comment by DC7IA** [comment]
This still does not work to move channels around in zones. Does "all lists" include zones as well?

**Comment by hmatuschek** [comment]
You can move channels around. However, it only works for single channels. For now moving around multiple items only works for lists in the main window. Not the dialogs. I reopen that issue to fix it. 

- [ ] Multiple selection/move in RX Group dialog
- [ ] Multiple selection/move in zone dialog
- [ ] Multiple selection/move in scan list dialog
- [ ] Multiple selection/move in roaming zone dialog

**Comment by hmatuschek** [comment]
I currently reworking the internal representation of the codeplug to allow for device specific settings. This will also include the way lists are edited. Fortunately, all lists will then be handled equally (this also saves a lot of code).

**Comment by hmatuschek** [comment]
Merged into master, needs some testing.
