### ISSUE TITLE
Implement separate AT-D868UV codeplug.

### ISSUE THREAD

**Issue by hmatuschek** [hmatuschek/qdmr#91]
The current AT-D878UV codeplug appears to work fairly with the older 868. So to support that radio properly:

- [x] Rename current AT-D878UV codeplug to D868UV
- [x] Derive AT-D878UV from 686. This involves overloading of some AnyTone codeplug specific functions (allocateXYZ method).
- [x] Move all 878 specific features to derived codeplug.
- [x] Verify 868 code-plug.
- [x] Cleanup radio detection code.
- [x] Test 868
- [x] Test 878

**Comment by ZeroChaos-** [comment]
this could *likely* be accomplished by simply making the unsupported features of the 878 hidden behind some flag, and when an 868 is read, don't set that flag, and don't show those config options.

**Comment by hmatuschek** [comment]
In fact I do it with the *magic* of OOP. I've created a branch called d868uv that contains these changes. Once I know it works and does not break the d878uv anymore (for now it does) I'll merge it into the master branch an release it as 0.7.0.

**Comment by hmatuschek** [comment]
Could you do me a favor? At the beginning of the d868uv.cc file, there are basic limits of the radio (number of channels, etc). Do they match the limits of your d868uv?

**Comment by hmatuschek** [comment]
Ok, it should be ready now. Needs some testing though.

**Comment by hmatuschek** [comment]
Appears to work. Close it for now.
