### ISSUE TITLE
Is it there any possibility to add support for Baofeng DM-1701

### ISSUE THREAD

**Issue by kimballen** [hmatuschek/qdmr#99]
Retevis rt84 is the same radio only difference is that the raidio identify itself as DM-1701 instead of rt84

**Comment by hmatuschek** [comment]
For now not. Although adding support is likely easy as it is similar to the supported RT3S, I need to have that radio in my hands to implement support for it. For now, I am not able to emulate this radio to study the codeplug format. Let alone to test the implementation.

So if am able to get my hands on this radio, I could add support for it.

**Comment by kimballen** [comment]
The codplug format is exactly the sam as rt84

**Comment by kimballen** [comment]
I have both radios

**Comment by hmatuschek** [comment]
I've checked the codeplug file at it appears to be almost identical to the one used by the RT3S CPS. That is, I can reverse engineer the codeplug from these files almost completely. However, I need some additional information to implement the read write operations. I need to check the memory write addresses (not stored in codeplug file) and if the transfer protocol remains the same. To do so, could you fire up wireshark and capture one codeplug write and read (https://wiki.wireshark.org/CaptureSetup/USB)? Possibly also a callsign db write? Could you then send me the pcapng and rdt files? With this, I will likely be able to implement the DM-1701 without having the device at hand. However, testing the codeplug in the end will be your job. ;-)

I am quiet busy right now so I will likely not be able to do this within the next two weeks or so.

**Comment by hmatuschek** [comment]
I've implemented the support for the DM-2017/RT82 and unified the classes supporting the TyT/Retevis radios. To this end, it will be pretty straight forward to support the DM-1701/RT84. I am in the process of cleaning everything up and testing the new implementation. If it works out, I'll add the DM-1701 support.

**Comment by hmatuschek** [comment]
I've created a new issue #136 to track the implementation progress. So I close this one as duplicate.
